scikit-build/scikit-build-core

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- src/scikit_build_core/_shutil.py
- src/scikit_build_core/cmake.py
- tests/test_cmake_config.py
- chore: updates pre-commit checks
- refactor: use `__fspath__` for cmake path
> refactor: use fspath for CMake

- pyproject.toml
Latest cattrs release restores pypy support. Might be able to start using it again.
> tests: use cattrs + pypy

- .github/workflows/ci.yml
- noxfile.py
- pyproject.toml
- tests/test_module_dir.py
- chore: ignore protocols when computing coverage
- tests: print failed module if `__dir__` does not work
> chore: minor fix to coverage

- .gitignore
- .pre-commit-config.yaml
- src/scikit_build_core/_logging.py
- src/scikit_build_core/builder/__init__.py
- src/scikit_build_core/builder/macos.py
- src/scikit_build_core/cmake.py
- tests/test_builder.py
- tests/test_cmake_config.py
- tests/test_simple_pure.py
Pulling out interesting changes from #15.
- chore: better gitignore
- chore: ignore package test naming
- fix: better logger message if detached
- chore: nicer ignore (from refurb)
- feat: verbose option, use defines
- fix: properly escape in CMake
- fix: support existing folders for the build dir
- feat: macOS version computation
> feat: starting builder helpers

- .pre-commit-config.yaml
- pyproject.toml
- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/setuptools/__init__.py
- src/scikit_build_core/setuptools/build_meta.py
- src/scikit_build_core/setuptools/extension.py
- tests/conftest.py
- tests/simple_setuptools_ext/CMakeLists.txt
- tests/simple_setuptools_ext/pyproject.toml
- tests/simple_setuptools_ext/setup.py
- tests/simple_setuptools_ext/src/main.cpp
- tests/test_setuptools_pep518.py
Implementing a setuptools backend based on pybind11's `cmake_example`.
Design features:
* `build_ext` must be added manually - setuptools overrides this already sadly, so we can't be assured we are first if we add it as an entrypoint.
* Vanilla `setuptools.setup` - could be wrapped to automatically add setup.
* Dependencies are declared dynamically when using the PEP 517 builder
A few things to do (after this PR):
* Caching doesn't work (PEP 517's environments break paths).
* Still no nice way to declare a module
* No internal modules yet like Python helpers
* No support for editable installs
* Only a single output module supported at the moment.
Todo in this PR:
> feat: setuptools extension backend

- .git_archival.txt
- .gitattributes
- .gitignore
- pyproject.toml
- src/scikit_build_core/__init__.py
- src/scikit_build_core/_version.pyi
If we did want to support VCS versioning, this is what it would look like. Not
sure it's worth it - the version is already single-sourced, and this requires a
bit more work to package. But, then again, not being able to forget to change
the version is really nice.
> feat: automatic versioning

- .github/codecov.yml
- README.md
- noxfile.py
- src/scikit_build_core/builder/builder.py
- tests/packages/simplest_c/CMakeLists.txt
- tests/test_simplest_c.py
This is probably the best I can do unless this is fixed upstream. FindPython doesn't respect pre-set SOABI values, so it has to be added in user code.
> fix: simple example PyPy support workaround

- src/scikit_build_core/builder/builder.py
Backported from a matching fix for scikit-build classic.
> fix: better support for FindPython

- src/scikit_build_core/builder/sysconfig.py
`pyodide-build` fails with `scikit-build-core`, because `scikit-build-core` tries to `stat()` the `libdir` given by `sysconfig`. I'm not sure what the bug is here; should we be able to stat `LIBDIR` under `pyodide-build`? I suspect not if we're pretending to be the target environment, but I'm not certain. 
This is a very specific fix, and I suspect there's a nicer way of generalising this to the  class of "this isn't a conventional Python distribution" errors. However, this patch as-it-stands fixes `pyodide-build`, so it's a starting point for a proper fix.
> fix: handle `PermissionError` in reading `libdir.is_dir()`

- pyproject.toml
- src/scikit_build_core/pyproject/init.py
- src/scikit_build_core/pyproject/sdist.py
- src/scikit_build_core/pyproject/wheel.py
- src/scikit_build_core/settings/cmake_model.py
- tests/conftest.py
- tests/packages/simple_pyproject_ext/pyproject.toml
- tests/test_skbuild_settings.py
Not supported in setuptools mode. Will take some thought there.
To test this or similar things, you can run:
```bash
pipx run build --wheel
PIP_FIND_LINKS="dist" pipx run build --wheel tests/packages/simple_pyproject_ext -o dist -C scikit-build.log-level=NOTSET
```
> feat: prettier logging with config setting

- .pre-commit-config.yaml
- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/builder/wheel_tag.py
- src/scikit_build_core/pyproject/wheel.py
- src/scikit_build_core/settings/skbuild_model.py
- src/scikit_build_core/setuptools/extension.py
- tests/packages/abi3_pyproject_ext/CMakeLists.txt
- tests/packages/abi3_pyproject_ext/abi3_example.c
- tests/packages/abi3_pyproject_ext/pyproject.toml
- tests/packages/abi3_setuptools_ext/CMakeLists.txt
- tests/packages/abi3_setuptools_ext/abi3_example.c
- tests/packages/abi3_setuptools_ext/pyproject.toml
- tests/packages/abi3_setuptools_ext/setup.py
- tests/test_builder.py
- tests/test_pyproject_abi3.py
- tests/test_setuptools_abi3.py
Supported in both modes. Should also support Pythonless wheels. Upstream request at https://gitlab.kitware.com/cmake/cmake/-/issues/24141. Closes #39.
Setuptools support is pretty bad due to wheel not having a public API, so in setuptools mode this should still be specified in the same way (pyproject.toml), rather than by setting `py_limited_abi`, so you get the proper wheel name. But it should still work as before, you just have to also set up the wheel name if you only specify `py_limited_api`.
> feat: support for setting python & abi tag (including limited API)

- src/scikit_build_core/builder/macos.py
- tests/test_builder.py
Was using the current instead of the Python compiled version of macOS as a min. Seen in https://github.com/scikit-build/cmake-python-distributions/pull/312.
> fix: incorrect min version of macOS

- src/scikit_build_core/setuptools/extension.py
- tests/packages/abi3_setuptools_ext/pyproject.toml
- tests/packages/abi3_setuptools_ext/setup.cfg
- tests/packages/abi3_setuptools_ext/setup.py
Using the native `bdist_wheel` setting for setuptools mode.
> refactor(setuptools): use native bdist_wheel setting for abi3

- src/scikit_build_core/cmake.py
This was missing, but is a good idea.
> fix: include --config when installing

- README.md
- pyproject.toml
- src/scikit_build_core/pyproject/sdist.py
- src/scikit_build_core/settings/skbuild_model.py
- tests/test_pyproject_pep517.py
- tests/test_pyproject_pep518.py
- tests/test_setuptools_pep517.py
Hey @henryiii,
This is rudimentary, but sets the scene for reproducible builds. I don't love the ergonomics and you seem to have a design vision here, so feel free to rewrite / ignore this if it needs another pass.
I'm not sure whether we need to offer an option for non-reproducible builds. I don't know enough about when you *wouldn't* want this to make a strong decision. But, it might also be something that the Hatch builder can deal with down the line, and sciki-build-core's backend can just be opinionated.
> feat: support reproducible sdist builds

- tests/test_pyproject_pep517.py
- tests/test_pyproject_pep518.py
- tests: tarfile on older Pythons was different.
- tests: adding failing test for wheel
> tests: reproducible

- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/builder/macos.py
- src/scikit_build_core/builder/wheel_tag.py
- src/scikit_build_core/setuptools/extension.py
- tests/test_builder.py
Closes #70. We still have to set MACOSX_DEPLOYMENT_TARGET in setuptools mode to avoid a warning there.
> fix: better macOS deployment target handling

- src/scikit_build_core/pyproject/sdist.py
~~I think this will fix the one test in cmake-python-distributions.~~ No, it didn't, but I think it's still a good idea.
> fix: don't touch mtime in non-reproducible mode

- .pre-commit-config.yaml
- pyproject.toml
- src/scikit_build_core/_compat/importlib.py
- src/scikit_build_core/builder/get_requires.py
- src/scikit_build_core/resources/__init__.py
- src/scikit_build_core/resources/known_wheels.toml
Quicker fallback to ninja if on a platform that is known to distribute ninja wheels. Expose similar info for CMake, too.
> fix: fallback to ninja sooner if on known platform

- .github/codecov.yml
- .github/workflows/ci.yml
- pyproject.toml
- src/scikit_build_core/cmake.py
- tests/test_cmake_config.py
- tests/test_program_search.py
- tests/test_pyproject_abi3.py
- tests/test_pyproject_pep517.py
- tests/test_pyproject_pep518.py
- tests/test_setuptools_abi3.py
- tests/test_setuptools_pep517.py
- tests/test_setuptools_pep518.py
- tests/test_simple_pure.py
Adding a Cygwin test. Closes #79. Not supported in setuptools mode yet.
> ci: add cygwin

- .github/codecov.yml
- .github/workflows/ci.yml
- README.md
- docs/changelog.md
About ready for a beta release.
> docs: preare for release

- pyproject.toml
- tests/test_setuptools_abi3.py
- tests/test_setuptools_pep517.py
- tests/test_setuptools_pep518.py
So it's easy to turn off the setuptools tests if needed.
> tests: add a mark for setuptools tests

- pyproject.toml
- tests/conftest.py
> tests: support running without pytest-virtualenv

- src/scikit_build_core/builder/sysconfig.py
This doesn't really matter (not used on Linux), but should fix the unit test.
> fix: conda prefix lib support

- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/pyproject/wheel.py
- tests/test_builder.py
Was based on the wrong assumption for ARCHFLAGS.
> fix: universal2 tags computation was incorrect

- src/scikit_build_core/pyproject/wheel.py
> fix: expand macos tags missing

- pyproject.toml
- tests/conftest.py
Some platforms don't care about isolated builds.
> tests: add marker for PEP 518

- README.md
- tests/packages/simple_pure/CMakeLists.txt
- tests/packages/simple_pure/simple_pure.cpp
> tests: require C++11 only

- tests/test_pyproject_pep517.py
It's passing there. Really need to figure out why Windows is sometimes different when making SDists.
> tests: xfail non-strict for conda-forge

- pyproject.toml
- tests/conftest.py
Useful for monitoring the testing environment and output wheel names.
> tests: add report header

- .flake8
- .github/workflows/ci.yml
- README.md
- pyproject.toml
- src/scikit_build_core/file_api/_cattrs_converter.py
- src/scikit_build_core/file_api/model/cache.py
- src/scikit_build_core/file_api/model/cmakefiles.py
- src/scikit_build_core/file_api/model/codemodel.py
- src/scikit_build_core/file_api/model/common.py
- src/scikit_build_core/file_api/model/directory.py
- src/scikit_build_core/file_api/model/index.py
- src/scikit_build_core/file_api/model/toolchains.py
- src/scikit_build_core/file_api/reply.py
- tests/constraints.txt
- tests/test_pyproject_pep518.py
Pulled out of #126 
- Fix a few missing values for CMake 3.15 FileAPI
- All FileAPI dataclasses now frozen
- Correct wrong minimum for `typing_extensions`
- Testing minimum requirements
- Rich not required in testing anymore (bad capping practices!)
I am not using/constraining the CMake package since it's broken on macOS 13 until recently. This also means I can't test 3.15 easily locally, but due to `ExeptionGroups` printing all errors at once, I didn't have to iterate!
> tests: min constraints without Windows

- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/builder/sysconfig.py
- fix: missing lib is warning, not error
- fix: warn if scripts included with potentially invalid shebangs
See #130.
> fix: warn on scripts with invalid shebangs

- .github/workflows/ci.yml
- src/scikit_build_core/cmake.py
- tests/test_cmake_config.py
- ci: MSVC 2019 test (2022 requires CMake 3.21+)
- fix: an issue with setting paths in the CLI on Windows
> fix: paths on Windows

- .github/CONTRIBUTING.md
- README.md
- tests/packages/abi3_pyproject_ext/CMakeLists.txt
- tests/packages/abi3_setuptools_ext/CMakeLists.txt
- tests/packages/filepath_pure/CMakeLists.txt
- tests/packages/simple_pure/CMakeLists.txt
- tests/packages/simple_pyproject_ext/CMakeLists.txt
- tests/packages/simple_setuptools_ext/CMakeLists.txt
- tests/packages/simplest_c/CMakeLists.txt
- tests/test_pyproject_pep517.py
- tests/test_pyproject_pep518.py
Updating examples ~and built-in backport~ to 3.25.
@jcfr and @thewtex, backporting was broken in 3.25 (and we need it for the SOABI fix from 3.26, and probably ABI3 if that's added, etc). See https://gitlab.kitware.com/cmake/cmake/-/issues/24185. If upstream is unwilling to fix it, we might have to maintain our own fork. :(
> chore: update to CMake 3.25

- pyproject.toml
- tests/conftest.py
- tests/test_pyproject_pep518.py
- tests/test_setuptools_pep518.py
Attempting to be a bit nicer on conda-forge.
> tests: split up isolated and virtualenv fixtures

- src/scikit_build_core/settings/skbuild_read_settings.py
- src/scikit_build_core/settings/sources.py
- tests/test_settings.py
- tests/test_skbuild_settings.py
> feat: did you mean?

- docs/changelog.md
- src/scikit_build_core/builder/get_requires.py
- tests/test_get_requires.py
Should allow conda-forge to reenable this test. Adding a little more debug logging.
> tests: clear CMAKE_GENERATOR

- src/scikit_build_core/build/sdist.py
- tests/test_pyproject_pep517.py
Our latest `awkward` deployment failed, and upon inspection I noticed that the file ordering of the sdist differed (producing a different SDist hash). This PR just consumes the file list, and sorts it before writing the archive.
> fix: sort filepaths for reproducibility

- .flake8
- tests/test_get_requires.py
- chore: manually list opinionated bugbear codes
- tests: fix subprocess mocking with packaging 22 with 10.16
> tests: fix issues mocking with packaging 22

- .github/workflows/ci.yml
PR for monitoring Python 3.12 support. We pass alpha 2, the removal of distutils!
> ci: Python 3.12 alpha 3

- src/scikit_build_core/builder/builder.py
This was fixed in CPython 3.8.7.
Would also be fixed by #148.
> fix: EXT_SUFFIX wrong before 3.8.7

- src/scikit_build_core/build/wheel.py
- tests/packages/simple_pyproject_ext/pyproject.toml
- tests/test_pyproject_pep517.py
- tests/test_pyproject_pep518.py
This fixes the `entry_points`, including `[project.scripts]`.
> fix: `entrypoints.txt` should be `entry_points.txt`

- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/builder/sysconfig.py
- tests/test_builder.py
Experimental cross-compile support.
> fix: Windows ARM cross-compile

- src/scikit_build_core/program_search.py
See https://github.com/scikit-build/scikit-build/pull/848.
> fix: handle local cmake dir for search

- tests/test_pyproject_pep518.py
The `python -m build --sdist` command used in this test creates an isolated venv which requires wheels for pybind11 and scikit_build_core[rich]:
```
[   45s] =================================== FAILURES ===================================
[   45s] ______________________________ test_pep518_sdist _______________________________
[   45s] 
[   45s]     @pytest.mark.integration
[   45s]     def test_pep518_sdist():
[   45s]         correct_metadata = textwrap.dedent(
[   45s]             """\
[   45s]             Metadata-Version: 2.1
[   45s]             Name: cmake-example
[   45s]             Version: 0.0.1
[   45s]             Requires-Python: >=3.7
[   45s]             Provides-Extra: test
[   45s]             Requires-Dist: pytest>=6.0; extra == "test"
[   45s]             """
[   45s] …
```
> Add isolated marker to test_pep518_sdist

- src/scikit_build_core/program_search.py
- tests/test_cmake_config.py
- tests/test_get_requires.py
- tests/test_program_search.py
> fix: avoid resolving cmake/ninja paths

- pyproject.toml
This tiny PR removes a duplicate code definition in the `ruff` configuration.
> fix: remove duplicate ruff code

- README.md
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/cmake.py
- src/scikit_build_core/settings/skbuild_model.py
- tests/test_cmake_config.py
- tests/test_pyproject_pep518.py
- tests/test_skbuild_settings.py
Support for custom build directory, opt-in. Using `FORCE` for the moment. Doesn't try to rewrite the paths for moving CMake yet, but the info for this is there in the new json file.
Maybe this shouldn't have a `cmake.` prefix? Edit: yes, looks like we could sync-up with meson-python if we just use `build-dir`, so let's go with that. See https://github.com/mesonbuild/meson-python/issues/275 for `builddir` -> `build-dir` there.
Might adjust this later. My thought is we can make this opt-in for now, then if we make it opt-out, we can protect the change on a minimum version selection.
> feat: build directory setting & reuse

- pyproject.toml
- src/scikit_build_core/build/_file_processor.py
- src/scikit_build_core/build/wheel.py
Some of our files are being skipped because they have "build" in the name. Noticed this in https://github.com/pypa/build/pull/573, and turns out problems were being masked here too.
> chore: fix ruff configuration

- noxfile.py
This is what I was thinking might be good enough.
Closes #189.
> tests: include cmake and ninja if missing in nox

- .pre-commit-config.yaml
- pyproject.toml
- src/scikit_build_core/builder/get_requires.py
Relative imports now work for typing-modules. :)
Closes #192.
> chore: bump ruff and mypy

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .gitmodules
- .pre-commit-config.yaml
- pyproject.toml
- src/scikit_build_core/resources/find_python/Copyright.txt
- src/scikit_build_core/resources/find_python/FindPackageHandleStandardArgs.cmake
- src/scikit_build_core/resources/find_python/FindPackageMessage.cmake
- src/scikit_build_core/resources/find_python/FindPython.cmake
- src/scikit_build_core/resources/find_python/FindPython/Support.cmake
- src/scikit_build_core/resources/find_python/FindPython3.cmake
- src/scikit_build_core/settings/skbuild_model.py
- tests/packages/simplest_c/CMakeLists.txt
- tests/test_skbuild_settings.py
This is now a port, see https://gitlab.kitware.com/cmake/cmake/-/issues/24185. Based on VTK's port at https://gitlab.kitware.com/vtk/vtk/-/blob/master/CMake/patches/3.23/FindPython/Support.cmake.
Support for the correct SOABI on PyPy and the Stable ABI are included.
Closes #148.
> fix: use dev version of FindPython

- .pre-commit-config.yaml
- pyproject.toml
- src/scikit_build_core/_compat/typing.py
- src/scikit_build_core/build/_wheelfile.py
- src/scikit_build_core/builder/wheel_tag.py
- src/scikit_build_core/cmake.py
- tests/conftest.py
Using self with mypy 1.0. Not requiring it at runtime. Typing extensions is required for <3.8 still, since it's used at runtime. Also enabling the shiny new `--show-fixes` in Ruff! :)
> chore: Self usage

- pyproject.toml
- tests/constraints.txt
This might help a little with packaging such as in #196.
> tests: allow pytest 7.0+ instead of 7.2+

- tests/test_cmake_config.py
Include other potential cmake aliases.
Closes: #209
> tests: support running tests with system cmake3 visible

- tests/test_pyproject_pep517.py
As per [this comment](https://github.com/scikit-build/scikit-build-core/pull/201#issuecomment-1467021496), `SOURCE_DATE_EPOCH` should be unset during this test. It might be necessary in some other tests, but so far no other tests were effected in #201.
> tests: support running in environments with SOURCE_DATE_EPOCH

- src/scikit_build_core/build/_wheelfile.py
- tests/test_wheelfile_utils.py
This applies the same sort of fix as applied to wheel in https://github.com/pypa/wheel/pull/511.
> fix: zipinfo regular file

- src/scikit_build_core/setuptools/build_meta.py
- tests/packages/abi3_setuptools_ext/pyproject.toml
- tests/packages/simple_setuptools_ext/pyproject.toml
This should be a safe API for third parties. Even if the setuptools wrapper is externalized.
This does require using `"scikit-build-core", "setuptools"` as requirements for now - this can be fixed later when there's a separate setuptools extension.
> feat: make sure setuptools wrapper is generic

- .pre-commit-config.yaml
- src/scikit_build_core/setuptools/extension.py
Fixes to upstream were released quicker than I thought! :)
> fix: version not a string (typing updates)

- src/scikit_build_core/build/__init__.py
- src/scikit_build_core/builder/get_requires.py
- src/scikit_build_core/metadata/fancy_pypi_readme.py
- src/scikit_build_core/metadata/setuptools_scm.py
- src/scikit_build_core/setuptools/build_meta.py
- tests/test_dynamic_metadata.py
- tests/test_get_requires.py
Followup to https://github.com/scikit-build/scikit-build-core/pull/197. Supports hooks providing dynamic dependencies. This does not (officially, anyway, without inspecting the call stack) provide a method supporting differentiating between calling hooks.
> feat: get_requires_for_dynamic_metadata

- README.md
- docs/configuration.md
- docs/getting_started.md
- src/scikit_build_core/settings/skbuild_model.py
- tests/test_skbuild_settings.py
Adding some missing tests and a bit of polish.
Also fixing a bug were 3.26.0 doesn't backport the 3.26.1 ABI3 fix.
> fix: CMake 3.26.0 (exactly) needs the backport too

- .gitignore
- .tito/packages/.readme
- .tito/tito.props
- scikit-build-core.spec
This will make it easier for maintainers to keep up to date with upstream package.
Note the version numbering is currently hard coded. It might be possible to retrieve it dynamically, but I'm not sure if it will work on copr. However this should not be much of an issue as long as we can get some notifications of the builds.
> Add rpm spec

- docs/configuration.md
This is from a small project of mine [`CmakeExtraUtils`](https://github.com/LecrisUT/CmakeExtraUtils) that makes the git version of `setuptools_scm` available for cmake projects as well.
> docs: Example of setting `setuptools_scm` and `DynamicVersion`

- .github/workflows/ci.yml
- noxfile.py
- pyproject.toml
- src/scikit_build_core/builder/sysconfig.py
- tests/test_setuptools_pep517.py
- tests/test_setuptools_pep518.py
Testing to see if I can fix the `address space needed by '_common.cpython-311-x86_64-msys.dll' (0x620000) is already occupied` failures. Switching to UCRT instead, currently disabling a few setuptools tests to get it to pass. Speeding up the tests, too.
> tests: fix msys failures

- src/scikit_build_core/_logging.py
- src/scikit_build_core/settings/skbuild_model.py
- tests/test_skbuild_settings.py
Since this isn't on by default and redirects to stderr, I think it's fine to default verbose to on.
> feat: change editable.verbose to default True

- docs/configuration.md
- src/scikit_build_core/resources/_editable_redirect.py
More important now that the default is True.
> fix: support SKBUILD_EDITABLE_VERBOSE of 0

- src/scikit_build_core/cmake.py
- tests/test_cmake_config.py
- tests/test_custom_modules.py
This warning is showing up, fix by moving the setting into -C.
> fix: unused prefix warning

- docs/getting_started.md
A typo in the documentation.
The tab was Cython | Cython, but the latter should have been fortran.
> typo on tab Fortran (was Cython)

- src/scikit_build_core/builder/builder.py
Fixes #283.  Ideally this needs to be fixed upstream.
> fix: only set the lib for FindPython on Windows

- docs/configuration.md
Note the `reproducible-builds` which in the documentation say:
> By default, scikit-build-core will respect SOURCE_DATE_EPOCH, and will lock the modification time to a reproducible value if it’s not set. You can disable reproducible builds if you prefer, however:
> ```
> [tool.scikit-build]
> sdist.reproducible = true
> ```
which didn't make sense to me? Am I wrong in changing this to `false`? Please advice.
> Doc updates

- .github/CONTRIBUTING.md
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/builder/generator.py
- src/scikit_build_core/builder/get_requires.py
- src/scikit_build_core/builder/sysconfig.py
- src/scikit_build_core/cmake.py
- tests/conftest.py
- tests/test_builder.py
- tests/test_fileapi.py
- tests/test_fortran.py
- tests/test_get_requires.py
- tests/test_pyproject_abi3.py
- tests/test_pyproject_pep517.py
- tests/test_pyproject_pep518.py
- tests/test_setuptools_abi3.py
- tests/test_setuptools_pep517.py
- tests/test_setuptools_pep518.py
- tests/test_simple_pure.py
This uses `sysconfig.get_platform()` to identify non-MSVC Windows platforms. Ninja is set to the default on non-MSVC.
> fix: specify platform properly for non-MSVC

- README.md
- src/scikit_build_core/cmake.py
Fix for now for `CMAKE_PREFIX_PATH` being ignored when used with emscripten (Pyodide). Tested in https://github.com/pybind/scikit_build_example/pull/84.
> fix: support prefix dir if toolchain has CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY

- pyproject.toml
- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/setuptools/build_cmake.py
- tests/packages/mixed_setuptools/CMakeLists.txt
- tests/packages/mixed_setuptools/pyproject.toml
- tests/packages/mixed_setuptools/setup.cfg
- tests/packages/mixed_setuptools/setup.py
Adds cmake_args, can be combined with `[build_cmake] cmake_args` and other ways to set it.
Also fixes keyword specification - the keyword functions are only supposed to be validators.
> feat(setuptools): adding cmake_args

- docs/changelog.md
- docs/configuration.md
- src/scikit_build_core/setuptools/build_cmake.py
Added one small feature (`cmake.source-dir`), so this is a 0.4.0 release.
> docs: prepare for 0.4.0

- README.md
- docs/configuration.md
- src/scikit_build_core/build/_wheelfile.py
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/settings/skbuild_model.py
- tests/test_pyproject_pep517.py
- tests/test_skbuild_settings.py
Fix #328. Follows the draft of PEP 639 more closely.
> fix: add License-file metadata entry

- README.md
- noxfile.py
- pyproject.toml
- src/scikit_build_core/_logging.py
- src/scikit_build_core/build/_init.py
- tests/conftest.py
- tests/packages/simple_pyproject_ext/pyproject.toml
- tests/packages/simple_pyproject_source_dir/pyproject.toml
- tests/test_logging.py
Pip doesn't allow rich to see the terminal, and because of this, the very narrow formatting makes the logs quite hard to read. Let's drop the option for now - if it's fixed in Pip, we can revisit.
> fix: drop rich logging/error

- docs/configuration.md
I'm not sure if we should also support `;` #336, but we should note that it supports spaces regardless.
> docs: CMAKE_ARGS supports space seperators

- src/scikit_build_core/builder/builder.py
Might be nice if we could indicate the target value too. But that will still be "truthful", so could be changed later.
> fix: allow CMake to detect if limited API is targeted

- src/scikit_build_core/build/wheel.py
Fixing #343, I think. Editable installs are not relocatable, so this should be fine.
> fix: editable path needs to be absolute

- src/scikit_build_core/build/_wheelfile.py
The header and filename need to match.
> fix: windows path correction

- README.md
- src/scikit_build_core/builder/builder.py
Discovery doesn't work when cross compiling, so it's important these are set.
Also need to set Python_SABI_LIBRARY separately.
> fix: abi3 backwards & Python_SABI_LIBRARY bug

- src/scikit_build_core/_shutil.py
Running with `logging.level = "DEBUG"`, `scikit-build-core` emits a log message listing environment variables for the build, like this:
```text
2023-06-05 00:48:26,822 - scikit_build_core - DEBUG - RUNENV:
SYSTEM_PULLREQUEST_SOURCECOMMITID=77b0ed1470cbf63d39ddae10915e96cea2804783
BUILD_QUEUEDBY=Microsoft.VisualStudio.Services.TFS
CONDA_SHLVL=1
LC_ALL=en_US.UTF-8
LD_LIBRARY_PATH=/usr/local/lib64:/opt/rh/gcc-toolset-12/root/usr/lib64:/opt/rh/gcc-toolset-12/root/usr/lib:/opt/rh/gcc-toolset-12/root/usr/lib64/dyninst:/opt/rh/  gcc-toolset-12/root/usr/lib/dyninst:/usr/local/lib
CONDA_EXE=/opt/miniforge/bin/conda
AGENT_HOMEDIRECTORY=/__a
SYSTEM_POSTLINESSPEED=10000
AGENT_USEWORKSPACEID=true
SYSTEM_STAGEDISPLAYNAME=__default
AGENT_VERSION=3.220.2
SYSTEM_JOBATTEMPT=1 …
```
> refactor: sort RUNENV debugging log output

- .gitignore
- docs/examples/downstream/nanobind_example/CMakeLists.txt
- docs/examples/downstream/nanobind_example/LICENSE
- docs/examples/downstream/nanobind_example/README.md
- docs/examples/downstream/nanobind_example/pyproject.toml
- docs/examples/downstream/nanobind_example/src/nanobind_example/__init__.py
- docs/examples/downstream/nanobind_example/src/nanobind_example_ext.cpp
- docs/examples/downstream/nanobind_example/tests/test_basic.py
- docs/examples/downstream/pybind11_example/CMakeLists.txt
- docs/examples/downstream/pybind11_example/LICENSE
- docs/examples/downstream/pybind11_example/README.md
- docs/examples/downstream/pybind11_example/pyproject.toml
- docs/examples/downstream/pybind11_example/src/main.cpp
- docs/examples/downstream/pybind11_example/src/scikit_build_example/__init__.py
- docs/examples/downstream/pybind11_example/tests/test_basic.py
- noxfile.py
- src/scikit_build_core/_shutil.py
- tests/conftest.py
Adding some downstream examples, lightly tested in CI.
> tests: add downstream examples

- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/builder/sysconfig.py
> fix: report correct ABI when cross-compiling

- pyproject.toml
- tests/conftest.py
- tests/test_fortran.py
- tests/test_pyproject_pep518.py
Adding a proper network marker. Tested locally by turning off my wifi. :)
See #368.
> tests: add network marker

- src/scikit_build_core/_shutil.py
- src/scikit_build_core/build/wheel.py
- tests/test_shutil.py
> fix: workaround for Windows Python 3.7 TemporaryDirectory bug

- .github/workflows/ci.yml
- pyproject.toml
Closes #382. The current `dev` isn't that helpful, so let's use it for this.
> chore: change dev extra to add extra requirements

- docs/index.md
- docs/migration_guide.md
Adding a page to the documentation about migrating from scikit-build classic. I'll keep updating this as I discover more while migrating various repos, then open it for review when I've found everything I expect to find.
> Add migration guide

- src/scikit_build_core/build/wheel.py
This now produces an unsused variable warning. Removing the warning.
> fix: remove SKBUILD_STATE unused message when building

- src/scikit_build_core/setuptools/build_cmake.py
> fix: avoid interfering with other setuptools plugins

- docs/getting_started.md
Two minor changes. Fixes a misspelling and broken markdown.
> Fix typo and invalid Markdown in getting_started.md

- src/scikit_build_core/build/_pathutil.py
- src/scikit_build_core/build/wheel.py
Partial fix to #437. The other part is revisiting the ignore patterns, probably using the default Python.gitignore, and having one for SDist and another for Wheel (TBD).
> fix: only link to valid module paths

- docs/configuration.md
- noxfile.py
- src/scikit_build_core/build/sdist.py
- src/scikit_build_core/settings/metadata.py
- tests/conftest.py
- tests/packages/simple_pyproject_ext/pyproject.toml
- tests/packages/simple_pyproject_source_dir/pyproject.toml
- tests/test_pyproject_pep517.py
- tests/test_pyproject_pep518.py
Normalize SDist names in 0.5+.
> fix: normalize sdist names

- docs/api/scikit_build_core.settings.rst
- docs/conf.py
- docs/configuration.md
- docs/examples/downstream/nanobind_example/pyproject.toml
- noxfile.py
- pyproject.toml
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/resources/toml_schema.json
- src/scikit_build_core/settings/documentation.py
- src/scikit_build_core/settings/json_schema.py
- src/scikit_build_core/settings/skbuild_model.py
- src/scikit_build_core/settings/skbuild_schema.py
- tests/test_schema.py
Adding a schema, generation from our dataclass-based config system, and the expected plugin.
> feat: add a schema for validate-pyproject

- pyproject.toml
> ci: fix fedora tests

- .github/workflows/ci.yml
- noxfile.py
- pyproject.toml
- src/scikit_build_core/_compat/tomllib.py
- tests/test_schema.py
Followup to https://github.com/scikit-build/scikit-build-core/pull/447 based on testing suggestion from @abravalheri.
> tests: validate schemas in regular testing

- docs/migration_guide.md
Self explanatory.  I followed the migration guide as written and got an error.
> Fix error in config names

- .packit.yaml
- docs/examples/downstream/main.fmf
- docs/examples/downstream/nanobind_example/main.fmf
- docs/examples/downstream/pybind11_example/main.fmf
- docs/examples/getting_started/cython/main.fmf
- docs/examples/getting_started/fortran/main.fmf
- docs/examples/getting_started/nanobind/main.fmf
- docs/examples/getting_started/pybind11/main.fmf
- docs/examples/test.sh
- Use fedora packages with `--no-index` and `--no-build-isolation`
- Enabled missing tests
- Placeholder for nanobind tests (Not yet packaged on fedora)
> ci: Fix Fedora CI

- src/scikit_build_core/builder/get_requires.py
- tests/test_get_requires.py
Fix #458.
@bennyrowland, I think this either fixes this or is a good start.
> fix: report cmake/ninja requried if already present

- docs/api/scikit_build_core.metadata.rst
- docs/configuration.md
- src/scikit_build_core/metadata/fancy_pypi_readme.py
- src/scikit_build_core/metadata/regex.py
- src/scikit_build_core/metadata/setuptools_scm.py
- src/scikit_build_core/settings/_load_provider.py
- src/scikit_build_core/settings/metadata.py
- tests/packages/custom_cmake/CMakeLists.txt
- tests/packages/custom_cmake/pyproject.toml
- tests/packages/dynamic_metadata/plugins/local/version/nested/__init__.py
- tests/test_custom_modules.py
- tests/test_dynamic_metadata.py
Based on https://github.com/scikit-build/dynamic-metadata/pull/1 (with some updates). Fixes https://github.com/scikit-build/scikit-build-core/issues/435.
This doesn't start using `tool.dynamic-metadata` yet, to give us room to change that. Plus we have to back-compat support `tool.scikit-build.metadata`, so might as well keep that as the only way to set this for now.
> feat: regex and dynamic-metadata rewrite

- docs/conf.py
https://github.com/pypa/setuptools/pull/4023 Fixes the issue
> fix: docs build

- docs/changelog.md
- noxfile.py
> docs: prepare for 0.5.0

- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/builder/sysconfig.py
Fixes https://github.com/scikit-build/scikit-build-core/issues/480. Also faster since it reduces the subprocess calls.
> fix: set NumPy include directory if known

- docs/configuration.md
> docs: `wheel.py.api` -> `wheel.py-api`

- pyproject.toml
- src/scikit_build_core/metadata/setuptools_scm.py
Trying to support setuptools_scm 8. See #496.
> fix: support setuptools_scm 8+

- docs/configuration.md
- src/scikit_build_core/build/wheel.py
> feat: add build_type and state to build-dir

- README.md
- docs/configuration.md
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_docs.py
- src/scikit_build_core/settings/skbuild_model.py
This is a rather common structure for mixed language projects.
> feat: include 'python' dir as an auto search path

- pyproject.toml
- src/scikit_build_core/metadata/setuptools_scm.py
`setputools_scm` still provides this private value for now. We are working on getting better, not-private support soon.
> Revert "fix: support setuptools_scm 8+ (#497)"

- src/scikit_build_core/program_search.py
Uses a simple `str.split('-msvc')` to extract the version number. `'-msvc'` in particular was chosen to allow for forwards-compatibility with future builds of MSVC CMake. I did not check for older versions as I do not expect they will be any less compatible and this is still an improvement on the current situation of no compatibility at all.
In my opinion, splitting on `-` should be sufficient and provide compatibility with any other builds of CMake with custom version strings. However, I did not do this as I'm not familiar with all of the possible builds of CMake out there and wanted to ensure functionality.
---
Update: Now parses using `str.split('-')` for extended compatibility. Thanks @henryiii 
---
Resolves: #500
> Parse CMake version strings containing '-'

- docs/configuration.md
- src/scikit_build_core/metadata/setuptools_scm.py
> fix: setuptools_scm 8 change

- docs/configuration.md
This clarifies that you have to also use `-v` to get the logging information set in the options. I am not sure if you also need the additional `-vv` settings depending on `logging.level`. Thoughts?
> doc: Clarify verbosity when using `pip`

- src/scikit_build_core/metadata/setuptools_scm.py
Fix #520.
This already is an error, so just making it a nicer error.
> fix: nicer error message when scm version missing

- src/scikit_build_core/setuptools/build_cmake.py
Dropping the DEBUG variable, it doesn't appear to be standard. Close #496.
> fix(setuptools): remove DEBUG envvar

- .pre-commit-config.yaml
- README.md
- noxfile.py
- pyproject.toml
- src/scikit_build_core/_version.pyi
- src/scikit_build_core/settings/documentation.py
- src/scikit_build_core/settings/sources.py
- src/scikit_build_core/setuptools/build_cmake.py
Ruff-format is [ready](https://astral.sh/blog/the-ruff-formatter).
- chore: some Ruff updates
- chore: use ruff-format
> chore: use ruff-format

- noxfile.py
Making testing things like #532 easier.
To see the error in that issue, run:
```bash
nox -s downstream -- https://github.com/cda-tum/mqt-core --editable -c "import mqt.core"
```
> chore: support editable installs in downstream nox check

- docs/configuration.md
The system platform is referenced as `platform_system` in the toml, not `sys_platform`. It is still computed by `sys.platform` however.
> Fix bad config option name in configuration.md

- .pre-commit-config.yaml
- docs/ext/conftabs.py
- pyproject.toml
- src/scikit_build_core/__init__.py
- src/scikit_build_core/_compat/typing.py
- src/scikit_build_core/_logging.py
- src/scikit_build_core/build/__init__.py
- src/scikit_build_core/builder/wheel_tag.py
- src/scikit_build_core/file_api/reply.py
- src/scikit_build_core/resources/_editable_redirect.py
- src/scikit_build_core/settings/json_schema.py
- src/scikit_build_core/settings/sources.py
- tests/test_fileapi.py
- tests/test_get_requires.py
- tests/test_json_schema.py
Adding a little and cleaning up. Tested `--preview` mode and made a few changes based on that, too.
> chore: add a bit to Ruff config

- src/scikit_build_core/resources/_editable_redirect.py
- tests/test_editable_unit.py
Fix https://github.com/scikit-build/scikit-build-core/issues/532. Non-package modules should not have submodule paths set. Builds on #545.
> fix: editable package imports fix

- src/scikit_build_core/build/_editable.py
- src/scikit_build_core/resources/_editable_redirect.py
- tests/test_editable_redirect.py
- tests/test_editable_unit.py
I believe this buggy template writing (bug introduced in 0.6.1) actually can't cause a real-world breakage, since the dir is not None if the options after it were set.
> fix: correct editable template & add more tests

- README.md
- docs/configuration.md
- noxfile.py
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/cmake.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/packages/simplest_c/CMakeLists.txt
- tests/test_pyproject_pep660.py
This adds support for editable.mode=inplace, which does an inplace CMake build, along with a simple editable mode .pth file. This has a lot of caveats (just like CMake inplace builds), but works better with some workflows and tools. It's certainly better than copying the output file back into the source, which is what some projects are currently doing. :)
> feat: add inplace mode for editable installs

- .distro/python-scikit-build-core.spec
This should fix the failing tests, I think.
> ci: fix spelling for Fedora

- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/test_skbuild_settings.py
Support namespaced config settings, `skbuild.X` now also works instead of just `X`.
> feat: support namespaced config settings

- src/scikit_build_core/build/wheel.py
This would help https://github.com/scikit-build/scikit-build-core/issues/571 not have shown an error (but in that case, multiple licenses is actually desired, and the custom `tool.scikit-build` setting should be used until PEP 639 goes somewhere).
Also fixes #571 by filtering out directory matches.
> fix: include license file entry in search

- .github/CONTRIBUTING.md
- .pre-commit-config.yaml
- README.md
- docs/configuration.md
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/builder/generator.py
- src/scikit_build_core/builder/get_requires.py
- src/scikit_build_core/cmake.py
- src/scikit_build_core/program_search.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/documentation.py
- src/scikit_build_core/settings/json_schema.py
- src/scikit_build_core/settings/skbuild_model.py
- src/scikit_build_core/settings/skbuild_read_settings.py
- src/scikit_build_core/setuptools/build_cmake.py
- tests/test_cmake_config.py
- tests/test_fileapi.py
- tests/test_fortran.py
- tests/test_get_requires.py
- tests/test_program_search.py
- tests/test_simple_pure.py
- tests/test_skbuild_settings.py
Close #583.
If `tool.scikit-build.minimum-version` is set, then this will require the correct setting here. If it's unset, it will just produce a warning if the old form is used (for now).
This is also an API change, but I think that's fine for a 0.x release unless someone needs back-compat, which I can add if needed.
> feat: cmake.version and ninja.version

- docs/configuration.md
- pyproject.toml
- src/scikit_build_core/_compat/typing.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/json_schema.py
- src/scikit_build_core/settings/skbuild_model.py
- src/scikit_build_core/settings/sources.py
- tests/test_schema.py
- tests/test_skbuild_settings.py
This PR allows reading environment variables to define CMake variable. This is especially useful when the set of valid values which a CMake variable can assume is either not known a priori, or is not finite, and so `overrides` is not really helpful. 
Simple example:
```toml
[tool.scikit-build]
cmake.define.FOO = {env = "FOO"}
```
Bumps `typing_extensions` to being required for Python 3.9+.
> feat: Setting CMake variables though environment variables

- docs/configuration.md
Just learned this the hard way
> doc: Warning about using `cmake.args` for defines

- docs/configuration.md
- src/scikit_build_core/settings/skbuild_read_settings.py
The necessary setting is `build-dir` not `build_dir`
> Fix '-' vs '_' in error message

- src/scikit_build_core/_shutil.py
From #629 
Maybe this level should be split for more granularity like:
- `status` for messages that should always be outputted like when it enters a `configure`/`build` stage, etc.
- `info` for tracing basic execution, like in this case what commands are run
> Make run command logged at info

- docs/configuration.md
Until #642 is addressed, specifying `-Cbuild-dir=""` is required to avoid "build-dir must be empty for editable inplace mode" error.
> doc: Clarify requirement for using "inplace" editable mode

- docs/configuration.md
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/settings/skbuild_read_settings.py
This ignores the build-dir setting when making an editable install. It's easier to configure and there's no benefit to the error.
> fix: editable install should ignore build-dir

- .github/workflows/ci.yml
- pyproject.toml
pylint is claiming that `|` is invalid in `.pyi`, which is incorrect.
> chore: have pylint ignore .pyi

- docs/cmakelists.md
I'm not super experienced with building Python modules with cmake, so it wasn't clear to me until I found it in a test what exactly "use SKBUILD_SOABI" meant until I found it in one of the tests, so I thought others might like to see the `set(Python_SOABI ${SKBUILD_SOABI})`.
> doc: be explicit about what it means to "use SKBUILD_SOABI"

- src/scikit_build_core/builder/wheel_tag.py
> fix: purelib should set py3 tag if unset

- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_read_settings.py
- src/scikit_build_core/settings/skbuild_schema.py
- tests/test_settings_overrides.py
This light-weight PR adds a special rule when overriding `cmake.define`, so that additivity is retained and orthogonal CMake defines are accommodated. Consider the following TOML excerpt:
```toml
[[tool.scikit-build.overrides]]
if.env.SET_FOO = "ON"
cmake.define.FOO = "1"
[[tool.scikit-build.overrides]]
if.env.SET_BAR = "ON"
cmake.define.BAR = "1"
```
As of now, this would result in `cmake.define` being `{"BAR": "1"}`. With the PR, `cmake.define` will be `{"FOO": 1, "BAR": "1"}`.
> feat: Preserve additivity of `cmake.define` across `overrides` tables

- README.md
- docs/configuration.md
- pyproject.toml
- src/scikit_build_core/build/_pathutil.py
- src/scikit_build_core/build/_wheelfile.py
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- tests/packages/simplest_c/CMakeLists.txt
- tests/test_editable_unit.py
- tests/test_simplest_c.py
As mentioned in our recent Community Meeting.
> fix!: exclude installed files if listed in exclude

- src/scikit_build_core/program_search.py
- tests/test_cmake_config.py
- tests/test_get_requires.py
- tests/test_prepare_metadata.py
- tests/test_program_search.py
cmake -E capabilities produces a machine-readable version, and is the intended way for programs to get the CMake version.
> fix: Use cmake -E capabilities instead of cmake --version

- README.md
- src/scikit_build_core/settings/skbuild_docs.py
Fix #676.
None was being replaced by `false`.
> docs: fix install strip default

- noxfile.py
- pyproject.toml
Pulling out a bit of cleanup, especially the better minimums.
> chore: some cleanup from uv branch

- .distro/plans/rpmlint.fmf
- .distro/python-scikit-build-core.rpmlintrc
- .distro/python-scikit-build-core.spec
- .packit.yaml
Closes #687
A few maintenance tasks:
- Fix rpmlint failures
- Drop F38 early from the CI
- Simplified the yaml file and maintenance using anchors
- Changed the base package to be `arch`-ful. This guarantees the build and tests are done on all architectures downstream
Will probably patch those for `scikit-build` as well.
> ci: Fedora CI maintenance

- .github/workflows/ci.yml
- docs/examples/getting_started/cython/CMakeLists.txt
- noxfile.py
- pyproject.toml
- tests/packages/cython_pxd_editable/pkg1/src/pkg1/one.pyx
- tests/packages/cython_pxd_editable/pkg2/src/pkg2/two.pyx
> ci: some changes from uv job

- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/constraints.txt
- tests/test_pyproject_pep518.py
Pulling out the API change from #637.
> feat(api): extra_settings for SettingsReader

- src/scikit_build_core/builder/wheel_tag.py
This was tagging as manylinux (at least sometimes).
> fix: ensure many/musl tags not selected

- src/scikit_build_core/build/__init__.py
- src/scikit_build_core/builder/get_requires.py
- src/scikit_build_core/setuptools/build_meta.py
- tests/test_get_requires.py
This is needed for https://github.com/scikit-build/scikit-build-core/pull/637#issuecomment-2050665306.
> refactor: GetRequires args changed

- pyproject.toml
- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/test_setuptools_pep517.py
This started happening recently, so protect ourselves from normalization here.
> tests: fix setuptools on Python 3.12

- docs/api/scikit_build_core.build.rst
- docs/api/scikit_build_core.settings.rst
- src/scikit_build_core/build/metadata.py
- src/scikit_build_core/build/sdist.py
- src/scikit_build_core/build/wheel.py
- tests/test_dynamic_metadata.py
Didn't notice this before, but this should be part of `build`.
> refactor: metadata is part of the build backend

- src/scikit_build_core/build/metadata.py
- tests/test_prepare_metadata.py
Validating only if scikit-build-core minimum-version is 0.9+ or not present.
> fix: validate description for 0.9+

- src/scikit_build_core/settings/sources.py
- tests/test_settings.py
> fix: support bools in config settings

- README.md
- docs/examples/downstream/nanobind_example/CMakeLists.txt
- noxfile.py
- pyproject.toml
- src/scikit_build_core/build/__init__.py
- tests/conftest.py
- tests/packages/sdist_config/pyproject.toml
- tests/packages/simple_purelib_package/pyproject.toml
- tests/packages/simple_pyproject_ext/pyproject.toml
- tests/packages/simple_pyproject_source_dir/pyproject.toml
- tests/test_custom_modules.py
- tests/test_editable.py
- tests/test_get_requires.py
- tests/test_pyproject_pep660.py
This adds `pathspec` as a required dependency. It makes the native backend easier to use, and is already there for hatchling, so it's really only an extra dependency for custom plugins and setuptools, so I think it's a valid tradeoff now that pyproject-metadata is vendored. 
Closes #280.
- **chore: remove a few unused pyproject-metadata's**
- **fix: always require pathspec**
> fix: always require pathspec

- README.md
- docs/changelog.md
- src/scikit_build_core/program_search.py
> fix: pyodide support by trying --version if -E fails

- docs/changelog.md
- src/scikit_build_core/program_search.py
> fix: unbound variable error

- .github/workflows/ci.yml
No Python 3.9 and below on macos-14, and min tests don't work on Apple Silicon either.
> ci: use macos-13 and 14 explicitly

- src/scikit_build_core/build/_wheelfile.py
- tests/test_prepare_metadata.py
- tests/test_simplest_c.py
- tests/test_wheelfile_utils.py
Not needed unless entrypoints is non-empty.
> fix: don't generate entrypoints.txt if none set

- src/scikit_build_core/builder/sysconfig.py
> fix: don't warn if lib not found on UNIX, just debug

- docs/build.md
- docs/faqs.md
Follow up to https://github.com/scikit-build/scikit-build-core/pull/698. The statement about producing `linux` wheels in build.md has been there since well before this bug was fixed. :) Hopefully this will make it a bit more discoverable.
> docs: add FAQ entry on repairing wheels

- docs/configuration.md
The example provided is not working anymore and will yield errors. This pull request will fix the issue.
> docs: fix example of configuration overrides in configuration.md

- noxfile.py
Pylint 3.2.0 reports an error in a .pyi file that 3.1.* didn't; we are ignoring pyi files since 3.0 since pylint doesn't handle them, but pylint is now ignoring the ignore. https://github.com/pylint-dev/pylint/issues/9623 (See boost-histogram if you want see how many errors pylint can spew about pyi files! We just have one.)
> chore: pin pylint for now

- README.md
- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- tests/test_builder.py
- tests/test_skbuild_settings.py
> feat: build.tool-args

- src/scikit_build_core/cmake.py
It looks like without this change, the leading whitespace with something like `-G 'Unix Makefiles'` being converted to ` 'Unix Makefiles'` makes CMake misinterpret this and not realize a generator is being provided.
> Strip whitespace around generator so that it's passed through correctly

- .distro/plans/rpminspect.fmf
- .packit.yaml
Didn't get to investigate why it is failing, but can disable it for a while to make the CI cleaner
> ci: Disable rpminspect on rawhide

- docs/configuration.md
https://github.com/scikit-build/scikit-build-core/pull/556 added the ability for -C options to be prefixed with `skbuild.`, but this was not noted in the configuration documentation. Add a note for this.
> fix(docs): note that -C options can be prefixed with `skbuild.`

- src/scikit_build_core/builder/sysconfig.py
Fixing the logic for finding a library to link to. Python fills the LIBRARY slot with .dll for some reason. CMake was fixing this by finding the `.lib` anyway, but now we feed it the right library to begin with, which fixes free-threading builds. Tests are currently just downstream in scikit-build-sample-projects until there's an easier way to get a free-threaded build in GHA, especially for Windows.
> fix: support windows free-threading

- src/scikit_build_core/build/wheel.py
When using setuptools_scm to obtain the version dynamic and
```toml
[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
```
is not set in pyproject.toml, the error message suggested that only a
static version is supported. Modify the error message to indicate both
are supported and suggest a fix in the dynamic case.
> fix: improve error message when metadata.version.provider not set

- docs/examples/getting_started/fortran/CMakeLists.txt
Fixing an issue seen in https://github.com/scikit-build/scikit-build-core/issues/761. Our simple example doesn't seem to catch the missing file, but it's clearly missing.
> docs: fix fortran example

- src/scikit_build_core/_logging.py
- src/scikit_build_core/build/_init.py
- src/scikit_build_core/setuptools/build_cmake.py
Causes too much logging in test output if user sets it higher than DEBUG. I think this was just to help the sdtputools backend.
> fix: logger set to DEBUG

- src/scikit_build_core/cmake.py
This commit fixes an issue when building a package with multiple targets.
**[Bug]** To give an example:
```toml
cmake.targets = ["target_A", "target_B", "target_C"]
```
In this case, scikit-build-core generates a sequence of build commands:
```bash
cmake --target target_A --config Release
cmake --target target_B
cmake --target target_C
```
Note that `--config Release` is lost since the second target.
**[Cause]** This originates from the case where `local_args` in `CMaker.build` in `cmake.py` is a generator rather than a list/tuple, and it becomes empty after being passed to `self._build` in [line 247](https://github.com/scikit-build/scikit-build-core/blob/83afeb2cad1f9f0168d92df6b9b0f9d43abd53a4/src/scikit_build_core/cmake.py#L247).
**[Fix]** This PR proactively converts `local_args` to a …
> fix: empty build arguments in multi-target build

- src/scikit_build_core/builder/sysconfig.py
> fix: logger shouldn't warn for missing lib on UNIX

- README.md
- src/scikit_build_core/settings/skbuild_docs.py
Just kept them around for a bit.
> docs: hide deprecated options in README

- README.md
- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/test_builder.py
- tests/test_skbuild_settings.py
> feat: move some cmake options to build section

- docs/configuration.md
- src/scikit_build_core/build/wheel.py
> feat: warn if cmake/ninja in build system requirements

- docs/examples/getting_started/fortran/pyproject.toml
> docs: use modern cmake/ninja version setting in Fortran example

- README.md
- docs/api/scikit_build_core.ast.rst
- docs/api/scikit_build_core.rst
- docs/api/scikit_build_core.settings.rst
- docs/configuration.md
- pyproject.toml
- src/scikit_build_core/ast/__init__.py
- src/scikit_build_core/ast/ast.py
- src/scikit_build_core/ast/tokenizer.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/auto_cmake_version.py
- src/scikit_build_core/settings/skbuild_model.py
- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/packages/fortran_example/pyproject.toml
- tests/test_auto.py
- tests/test_cmake_ast.py
- tests/test_skbuild_settings.py
Close #777.
This is on by default for 0.10+. Setting "CMakeLists.txt" explicitly though will force it to be found, while the default will fallback on 3.15+.
> feat: auto cmake version

- docs/projects.md
- src/scikit_build_core/_logging.py
- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/test_skbuild_settings.py
Clean up warning/error printout. Warnings are not repeated.
> chore: nicer error/warning printer

- docs/configuration.md
- src/scikit_build_core/metadata/regex.py
This allows capturing the version when typing the version attribute using `__version__: str = "1.0.1"` as well.
> improve version regex to capture typed version attributes

- docs/configuration.md
- src/scikit_build_core/metadata/regex.py
- tests/test_dynamic_metadata.py
First 3 lines of #765. Makes `"{value}"` configurable.
> feat: support multipart regex

- docs/overrides.md
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_read_settings.py
- src/scikit_build_core/settings/skbuild_schema.py
- tests/test_settings_overrides.py
Close #766.
Will make sure it works for something like pybind11 ~~first~~. Will need one more thing, so making this a followup.
> feat: from-sdist for overrides

- docs/overrides.md
- src/scikit_build_core/build/_init.py
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_read_settings.py
- src/scikit_build_core/settings/skbuild_schema.py
- tests/conftest.py
- tests/packages/broken_fallback/CMakeLists.txt
- tests/packages/broken_fallback/main.c
- tests/packages/broken_fallback/pyproject.toml
- tests/test_broken_fallback.py
- tests/test_settings_overrides.py
> feat: if failed (retry)

- docs/api/scikit_build_core.settings.rst
- src/scikit_build_core/settings/skbuild_overrides.py
- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/test_settings_overrides.py
This is getting large, so pulling it out into a file.
> refactor: pull out overrides to seperate file

- README.md
- docs/configuration.md
- noxfile.py
- src/scikit_build_core/_compat/importlib/metadata.py
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/builder/get_requires.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- tests/packages/broken_fallback/pyproject.toml
- tests/test_broken_fallback.py
- tests/test_skbuild_settings.py
Adding a `fail = true` setting. One possible use:
```toml
[[tool.scikit-build.overrides]]
if.python-version = ">=3.13"
fail = true
```
This will be nicer once we allow customizing the error message.
See #112.
> feat: add fail setting

- README.md
- docs/configuration.md
- src/scikit_build_core/build/__init__.py
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/errors.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- tests/packages/abi3_pyproject_ext/pyproject.toml
- tests/test_broken_fallback.py
- tests/test_pyproject_abi3.py
- tests/test_skbuild_settings.py
See #112.
This includes `.format()` so that items can be added here later in a backward-compatible way.
> feat: add messages config for failure/success

- docs/configuration.md
- src/scikit_build_core/metadata/regex.py
- tests/test_dynamic_metadata.py
This adds the ability to post-process regex to remove "dev0" or similar. Closes #765.
> feat: add `remove=` postprocess to regex

- src/scikit_build_core/builder/builder.py
See https://github.com/scikit-build/scikit-build-core/pull/828. CMake will not understand the epoch, so not including it. It's still in `SKBUILD_PROJECT_FULL_VERSION`.
> fix: strip epoch from SKBUILD_PROJECT_VERSION

- src/scikit_build_core/builder/get_requires.py
> fix: detect manual generator setting for get_requires

- README.md
- docs/overrides.md
- src/scikit_build_core/builder/sysconfig.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_overrides.py
- src/scikit_build_core/settings/skbuild_schema.py
- tests/test_settings_overrides.py
~~I think this won't work on Windows yet, we'll need to find the flags another way there, I think.~~ Now uses packaging.tags. Close #770.
> feat: if for free-threading

- docs/changelog.md
- docs/overrides.md
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/auto_requires.py
- src/scikit_build_core/settings/skbuild_overrides.py
- src/scikit_build_core/settings/skbuild_schema.py
- tests/test_auto.py
- tests/test_settings_overrides.py
This adds an `if.scikit-build-version`, and makes sure it can be used to gate features not yet implemented. This should help with #769 by providing a way to support old scikit-build-core's on Python 3.7 even after we drop support.
Also fixes auto minimum-version to respect markers.
> feat: if.scikit-build-version

- src/scikit_build_core/build/_file_processor.py
- tests/test_file_processor.py
If .git is a file instead of a directory (such as when you are building in a submodule), scikit-build-core will currently crash because a NotADirectoryError is thrown instead of a FileNotFoundError. This PR accounts for the resulting exception (NotADirectoryError) instead of crashing.
Another option instead of hardcoding this list would be to catch the more general `OSError`. However, I did not do that, because I am worried about silently swallowing too broad of a class of exceptions.
I wrote a unit test and also tested the fix [against the project][1] where I encountered this.
[1]: https://github.com/scikit-build/scikit-build-core/blob/main/.github/CONTRIBUTING.md#testing-a-project-with-a-branch--main
(By the way, this project is very helpful, thank you. The fact that I encountered this …
> Fix crash when building inside a submodule

- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/test_skbuild_settings.py
Fixing an issue using `cmake.minimum-version`.
> fix: min version logic issue

- src/scikit_build_core/build/_file_processor.py
Currently if a file matches the explicit `sdist.include` it is included twice in the source distribution.
This causes an error with some package managers such as `uv` (See https://github.com/abetlen/llama-cpp-python/issues/1670#issuecomment-2284603172).
> fix: Files included twice when they match `include_spec`

- .pre-commit-config.yaml
- src/scikit_build_core/build/_editable.py
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/resources/_editable_redirect.py
- tests/test_editable.py
- tests/test_editable_redirect.py
- tests/test_editable_unit.py
Attempting to fix: https://github.com/scikit-build/scikit-build-core/issues/866
I'm passing down wheel.install-dir to the editable redirect script and appending it to DIR so that rebuilds happen in the correct path. This worked for me in a local testing environment, but I'm not familiar with this codebase, so I don't know if this is an optimal solution.
> Editable installs now respect the value of wheel.install-dir

- src/scikit_build_core/cmake.py
Fix https://github.com/scikit-build/scikit-build-core/issues/869 by detecting a moved isolated environment and issuing `--fresh`. Also go ahead and use this for the moved source dir case too.
> fix: automatically refresh the cache when required

- src/scikit_build_core/build/_file_processor.py
Previously, sdist.exclude and the built-in EXCLUDE_LINES were prepended to the list of .gitignore rules. However, a common pattern of using * to exclude everything and then using !-rules to list what should be included renders this feature useless.
This commit changes the behavior of each_unignored_file to sequentially consider the following sets of independent rules:
1. Explicit inclusions
2. Explicit exclusions
3. Global exclusions from the .gitignore files
4. The built-in exclusions
5. Nested exclusions from .gitignore
Fixes #871
> fix: sdist.exclude takes precedence over .gitignore

- src/scikit_build_core/metadata/regex.py
- tests/test_dynamic_metadata.py
Hello together.
I've been trying to use the `remove` settings key for the `regex` metadata plugin and noticed, that it has been non-functional for me. To me, it looks like the plugin acquires the wrong value from the settings dictionary (`result` instead of `remove`). This PR intends to change this to what I believe is correct.
> fix: use correct settings key to remove parts of the version in regex metadata plugin

- noxfile.py
- pyproject.toml
- src/scikit_build_core/resources/_editable_redirect.py
Proposed fix for https://github.com/scikit-build/scikit-build-core/issues/893.
- **fix: nox + uv downstream improvements**
- **fix: editable subpackage issue**
> fix: editable subpackage

- README.md
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- src/scikit_build_core/settings/skbuild_read_settings.py
> fix: only strip Release and MinSizeRel builds by default

- .github/codecov.yml
- docs/changelog.md
Preparing for next bug-fix release.
> chore: prepare for 0.10.6

- docs/overrides.md
- src/scikit_build_core/build/__init__.py
Reported in https://github.com/rapidfuzz/RapidFuzz/pull/397.
This avoids declaring the optional hooks if there's a good chance it can't be computed reliably. Having an override with `failed` can't be computed without trying to build.
> fix: avoid providing prepare-metadata methods if rebuild is True

- docs/overrides.md
- src/scikit_build_core/settings/skbuild_overrides.py
- tests/test_settings_overrides.py
Noticed in https://github.com/rapidfuzz/RapidFuzz/pull/397.
> fix: support negative envvar values correctly

- .github/workflows/ci.yml
- noxfile.py
From #917. Also fixing the docs job to use the correct scikit-build-core (local) version.
> chore: vendor updates

- docs/configuration.md
- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/json_schema.py
- src/scikit_build_core/settings/skbuild_model.py
- tests/packages/cmake_defines/CMakeLists.txt
- tests/packages/cmake_defines/pyproject.toml
- tests/test_cmake_config.py
- tests/test_skbuild_settings.py
Adds support for specifying CMake lists in `cmake.define` using TOML lists:
```
[tool.scikit-build.cmake.define]
ONE_LEVEL_LIST = [
"Foo",
"Bar",
"ExceptionallyLargeListEntryThatWouldOverflowTheLine",
"Baz",
]
NESTED_LIST = [ "Apple", "Lemon;Lime", "Banana" ]
```
Escapes semicolons in list items so as to allow nested lists.
Fixes #874
> Support TOML lists in cmake.define

- .distro/plans/examples.fmf
- .distro/plans/smoke.fmf
- .distro/tests/smoke.fmf
- docs/examples/downstream/nanobind_example/main.fmf
- docs/examples/downstream/pybind11_example/main.fmf
- docs/examples/getting_started/abi3/main.fmf
- docs/examples/getting_started/c/main.fmf
- docs/examples/getting_started/cython/main.fmf
- docs/examples/getting_started/fortran/main.fmf
- docs/examples/getting_started/nanobind/main.fmf
- docs/examples/getting_started/pybind11/main.fmf
- docs/examples/getting_started/swig/main.fmf
- docs/examples/test.sh
- hotfix for #799 (doesn't need new release, I've already pushed the changes downstream)
- reformat the fmf files to look more like yaml
- install doc examples in their own `venv`
> ci: tmt tests improvements

- docs/cmakelists.md
Normalize some terminology and expand some incomplete guidance.
> Clarify docs for activating stable ABI

- .pre-commit-config.yaml
- CITATION.cff
This adds the long requested citation. I think we should also add a Zenodo citation too. Note that requesting a paper instead of the software project is discouraged; there's also a way to request both be cited, etc.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
Close #738.
> chore: add citation

- docs/cmakelists.md
I guess `cmake.module` should correspond to `CMAKE_MODULE_PATH` and `cmake.prefix` should correspond to `CMAKE_PREFIX_PATH`, otherwise, it's confusing.
> docs: correct the order of entry-points and CMake variables

- .pre-commit-config.yaml
- pyproject.toml
- src/scikit_build_core/_compat/importlib/metadata.py
- src/scikit_build_core/_logging.py
- src/scikit_build_core/ast/ast.py
- src/scikit_build_core/ast/tokenizer.py
- src/scikit_build_core/build/__init__.py
- src/scikit_build_core/builder/get_requires.py
Hi! I just released Ruff 0.8.0. This release removes a few rules that had been deprecated for a few releases, so Ruff 0.8.0 would have started emitting warnings when linting `scikit-build-core` due to the fact that you have some of these now-removed rules explicitly ignored in your Ruff config.
This PR gets rid of the removed rules from your Ruff config. There's also some additional changes made here due to some rule stabilisations in this release -- let me know if these are unwelcome, and I can add them to the `tool.ruff.lint.ignore` list:
- Several files have had minor changes made due to the stabilisations of [`unsorted-dunder-all`](https://docs.astral.sh/ruff/rules/unsorted-dunder-all/) (`RUF022`) and [`unsorted-dunder-slots`](https://docs.astral.sh/ruff/rules/unsorted-dunder-slots/) …
> Bump Ruff to 0.8.0

- docs/cmakelists.md
This fixes instructions originally introduced in 48a879b ("docs: some updates (#334)", 2023-05-23)
> docs: Fix instructions to check if `Development.SABIModule` was requested

- docs/cmakelists.md
- src/scikit_build_core/builder/builder.py
- tests/packages/abi3_pyproject_ext/CMakeLists.txt
> feat: SKBUILD_SABI_VERSION

- .pre-commit-config.yaml
- src/scikit_build_core/build/_wheelfile.py
- src/scikit_build_core/build/generate.py
- src/scikit_build_core/setuptools/build_cmake.py
- src/scikit_build_core/setuptools/wrapper.py
- tests/test_builder.py
Update to Ruff 0.9. Fix a test.
> chore: update to Ruff 0.9

- .distro/python-scikit-build-core.spec
- .pre-commit-config.yaml
- README.md
- noxfile.py
- pyproject.toml
- src/scikit_build_core/_vendor/pyproject_metadata/__init__.py
- src/scikit_build_core/_vendor/pyproject_metadata/constants.py
- src/scikit_build_core/_vendor/pyproject_metadata/errors.py
- src/scikit_build_core/_vendor/pyproject_metadata/project_table.py
- src/scikit_build_core/_vendor/pyproject_metadata/pyproject.py
- src/scikit_build_core/build/metadata.py
- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- tests/conftest.py
- tests/packages/pep639_pure/pyproject.toml
- tests/test_prepare_metadata.py
- tests/test_pyproject_pep517.py
- tests/test_pyproject_pep518.py
- tests/test_schema.py
- tests/test_skbuild_settings.py
- tests/test_wheelfile_utils.py
> feat: update vendored pyproject-metadata

- src/scikit_build_core/_shutil.py
- src/scikit_build_core/program_search.py
Protection for #955, though I can't reproduce.
> fix: timeout checking cmake/ninja

- src/scikit_build_core/build/_file_processor.py
- src/scikit_build_core/build/_pathutil.py
- src/scikit_build_core/build/sdist.py
- src/scikit_build_core/build/wheel.py
- tests/test_editable_unit.py
> fix: ignore build dir automatically

- src/scikit_build_core/program_search.py
Make sure this doesn't trigger unless it's locked up. Windows can take more than 2 seconds to respond in our CI.
> fix: longer timeout on Windows

- docs/build.md
- docs/crosscompile.md
> docs: add some notes and warnings about cross-compilation

- src/scikit_build_core/build/_editable.py
- src/scikit_build_core/build/_pathutil.py
- tests/packages/navigate_editable/CMakeLists.txt
It works fine with normal install `pip install .` but not for editable install `pip install -e .`
I got the error below without this fix because it can't handle hidden file's extension corretly:
```
File "/opt/miniconda3/envs/pyapl/lib/python3.12/site-packages/scikit_build_core/build/_pathutil.py", line 31, in path_to_module
path = path.with_name(path.name.split(".", 1)[0])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/miniconda3/envs/pyapl/lib/python3.12/pathlib.py", line 634, in with_name
raise ValueError("Invalid name %r" % (name))
ValueError: Invalid name ''
```
For example, if it's `.clang-tidy`, the original splitting `path.name.split(".", 1)[0]` results empty string.
> fix: path_to_module to handle hidden files (e.g. .clang-tidy) correctly

- README.md
- docs/configuration/dynamic.md
- src/scikit_build_core/builder/get_requires.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- tests/packages/dynamic_metadata/build_requires_project.toml
- tests/test_dynamic_metadata.py
TODO:
- should we copy hatchling's implementation or resolve it only if `hatchling` is added to dependency?
> feat: Add new field `build.build-requires`

- README.md
- docs/configuration/search_paths.md
- docs/guide/cmakelists.md
- docs/index.md
- src/scikit_build_core/builder/builder.py
- src/scikit_build_core/cmake.py
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/skbuild_model.py
- tests/packages/custom_cmake/CMakeLists.txt
- tests/packages/custom_cmake/extern/custom_cmake_testing_stuff/cmake_root/ExampleRootConfig.cmake
- tests/packages/custom_cmake/extern/pyproject.toml
- tests/test_skbuild_settings.py
- Add a new page on all the search logics
- Encourage the usage of `cmake.root` over `cmake.prefix`
Closes #831 
Closes #885
Relates to #860 (still keeping it open because it doesn't address the specific issue)
> feat: Rework CMake search path settings

- .readthedocs.yml
At the time of writing, the "latest" version of the scikit-build-core documentation website (https://scikit-build-core.readthedocs.io/en/latest/) shows documentation pages from an ancient version. This pull request _should_ fix that.
https://docs.readthedocs.com/platform/stable/build-customization.html#unshallow-git-clone
> fix: RTD builds when last git tag is more than 50 commits behind

- .github/workflows/ci.yml
- docs/about/changelog.md
Adding CI for 3.14 and linux ARM. Other minor updates, including dropping a few of the docs jobs to avoid them triggering too many API calls and using pypy 3.10 more than 3.9.
> ci: add ARM & 3.14 testing

- .github/workflows/ci.yml
- README.md
- noxfile.py
- pyproject.toml
Minor cleanup. Require pytest 7.2+.
> chore: bump pytest version and include pytest-xdist

- docs/configuration/index.md
- Changed `cmake.verbose` mention to `build.verbose`
- Clarified that CMake configure output is always printed, and does not require any additional options. That's the main usage usually.
> doc: Clarify verbosity options

- .pre-commit-config.yaml
- src/scikit_build_core/format.py
- src/scikit_build_core/hatch/plugin.py
- src/scikit_build_core/resources/_editable_redirect.py
- src/scikit_build_core/settings/sources.py
- tests/test_builder.py
- tests/test_pyproject_pep660.py
- tests/test_skbuild_settings.py
Working around a bug with the TC checks and submodules (https://github.com/astral-sh/ruff/pull/16186).
> chore: bump to ruff 0.10, work around bug

- src/scikit_build_core/program_search.py
See https://github.com/pyodide/pyodide/pull/5510.
> fix: increase timeout on CI

- pyproject.toml
Deprecation message introduced in Python3.14. Filed upstream issue: https://github.com/python-attrs/cattrs/issues/635
> fix: Ignore deprecation message from cattrs

- docs/examples/getting_started/pybind11/CMakeLists.txt
- docs/guide/getting_started.md
See https://github.com/mlc-ai/xgrammar/pull/249.
> docs: fix incorrect name (PYBIND11_NEWPYTHON)

- docs/configuration/search_paths.md
The documentation provides an incorrect example for disabling `site-packages` when searching for CMake configs. It should align with the value specified in the [schema](https://github.com/scikit-build/scikit-build-core/blob/main/src/scikit_build_core/resources/scikit-build.schema.json#L414)
> docs: fix incorrect configuration example

- .github/workflows/ci.yml
- docs/examples/getting_started/c/CMakeLists.txt
Trying to track down a Windows bug where we can't find the correct library to link to but FindPython can, but only when Interpreter is specified.
> ci: restore example builds for Windows/macOS

- docs/about/changelog.md
Let's not hold up work on 0.12 any longer. We can always branch if we need more 0.11 patches.
> docs: prepare for 0.11.1

- docs/guide/build.md
Noticed while reading up on some of the options.
> docs: fix typo in macOS repair wheel tool name

- docs/conf.py
- docs/guide/dynamic_link.md
- docs/index.md
I split the general documentation from #1009
> docs: document how to deal with dynamic linking

- docs/api/scikit_build_core.metadata.rst
- docs/configuration/dynamic.md
- pyproject.toml
- src/scikit_build_core/build/metadata.py
- src/scikit_build_core/builder/_load_provider.py
- src/scikit_build_core/builder/get_requires.py
- src/scikit_build_core/metadata/__init__.py
- src/scikit_build_core/metadata/fancy_pypi_readme.py
- src/scikit_build_core/metadata/regex.py
- src/scikit_build_core/metadata/template.py
- tests/packages/dynamic_metadata/plugin_project.toml
- tests/test_dynamic_metadata.py
Implementation of https://github.com/scikit-build/dynamic-metadata/issues/21. Mentioned in https://discuss.python.org/t/partially-dynamic-project-metadata-proposal-pre-pep/88608.
~~TODO: support specifying a non-dynamic field. It should not be an error if it exists already!~~
> feat: add template dynamic-metadata plugin and support requesting other fields

- src/scikit_build_core/settings/skbuild_read_settings.py
- tests/test_skbuild_settings.py
Fix https://github.com/scikit-build/scikit-build-core/issues/912.
Now envvar and config options won't trigger the error, only statically defined ones will. And you can override a static option with the renamed new option. 
Also minor fix for a missing `env=env` passthrough for the API.
> fix: support overriding renamed options

- src/scikit_build_core/settings/documentation.py
- src/scikit_build_core/settings/skbuild_docs.py
- src/scikit_build_core/settings/skbuild_model.py
> doc: Add a field metadata to the setting fields 

- tests/test_dynamic_metadata_unit.py
- tests/test_settings_docs.py
Also adding back a couple of test files that I wrote but missed adding in previous PRs:
* #1051
* #1047
> tests: add missing test files

- pyproject.toml
- tests/test_schema.py
- tests/test_simplest_c.py
> tests: a few better ids

- src/scikit_build_core/builder/builder.py
- tests/packages/dynamic_metadata/CMakeLists.txt
Fix #1061. All paths need to be of type Path so they are converted to CMake paths and the type is correct (PATH).
> fix: make sure all paths are CMake paths

- pyproject.toml
- src/scikit_build_core/_logging.py
- src/scikit_build_core/build/__main__.py
- tests/test_broken_fallback.py
- tests/test_build_cli.py
- tests/test_printouts.py
- tests/test_skbuild_settings.py
Adding a couple of potentially useful build commands:
```
python -m scikit_build_core.build requires
python -m scikit_build_core.build metadata
```
"requires" prints out the full build requirements. "metadata" reads the project table, runs dynamic metadata, and then prints the new project table in json form; it may need the requirements installed (which is why I added both commands). Maybe it needs another name, actually, I could see someone wanting the METADATA contents, perhaps.
Like the other commands, these are somewhat experimental and subject to change.
Warning/error messages now print to stderr.
> feat: add a couple of build commands

- docs/about/changelog.md
> docs: prepare for 0.11.2

- src/scikit_build_core/program_search.py
- tests/test_build_cli.py
Fix for https://github.com/conda-forge/scikit-build-core-feedstock/pull/63.
> tests: work when CMAKE_GENERATOR is set

- tests/conftest.py
See https://github.com/pypa/virtualenv/pull/2868. It looks easy to check the virtualenv version, so let's just do that.
> tests: remove no-wheel based on virtualenv version

- src/scikit_build_core/metadata/__init__.py
- tests/test_dynamic_metadata_unit.py
Fixes issue described in https://github.com/scikit-build/scikit-build-core/pull/1047#issuecomment-2850523570.
> fix: add scripts to _DICT_STR_FIELDS for dynamic metadata.

- .distro/python-scikit-build-core.spec
- .github/workflows/ci.yml
- pyproject.toml
- src/scikit_build_core/_compat/argparse.py
- src/scikit_build_core/build/__main__.py
- src/scikit_build_core/builder/wheel_tag.py
- src/scikit_build_core/file_api/_cattrs_converter.py
- src/scikit_build_core/file_api/query.py
- src/scikit_build_core/file_api/reply.py
> chore: add 3.14 beta 1 support

- .github/workflows/nightlies.yml
See https://github.com/scientific-python/upload-nightly-action/issues/124.
> ci: upload nightly wheels to Anaconda

- .github/workflows/ci.yml
- README.md
- docs/about/changelog.md
- docs/about/projects.md
- docs/conf.py
- docs/data/projects.toml
- docs/index.md
- docs/reference/cli.md
- pyproject.toml
- src/scikit_build_core/build/__main__.py
- src/scikit_build_core/builder/wheel_tag.py
- src/scikit_build_core/file_api/_cattrs_converter.py
- src/scikit_build_core/file_api/query.py
- src/scikit_build_core/file_api/reply.py
Adding a reference page for this.
There's also a `pathlib._local.Path` warning when building the docs we should try to fix eventually.
Also preparing for a patch release with the 3.14 support and a bug fix.
> docs: add a reference page for CLI utilities

- README.md
- docs/reference/configs.md
- src/scikit_build_core/resources/scikit-build.schema.json
- src/scikit_build_core/settings/documentation.py
- src/scikit_build_core/settings/json_schema.py
- src/scikit_build_core/settings/skbuild_docs_readme.py
- src/scikit_build_core/settings/skbuild_docs_sphinx.py
- src/scikit_build_core/settings/skbuild_model.py
- tests/test_settings_docs.py
Quite a lot to go through on this one
> chore: Refactor the documentation to use single-line summaries

- src/scikit_build_core/metadata/__init__.py
Noticed in https://github.com/scikit-build/dynamic-metadata/pull/39.
> fix: typo in license-files

- docs/reference/cli.md
- src/scikit_build_core/__main__.py
- src/scikit_build_core/_logging.py
- src/scikit_build_core/build/__main__.py
Noticed these issues, and adding a table of contents like feature. If we expand this in the future, the default should still print out help, so it's forward compatible.
> fix: some cli issues resolved

- src/scikit_build_core/builder/_load_provider.py
- src/scikit_build_core/builder/sysconfig.py
- src/scikit_build_core/file_api/model/codemodel.py
- tests/test_setuptools_abi3.py
Not sure why some jobs are failing, so let's just add the fixes found here.
- **fix: support graalpy**
- **fix: better abiflags impl, 3.14 ready**
- **fix: commandFragments is optional**
> fix: graalpy (without added CI)

- src/scikit_build_core/build/wheel.py
- src/scikit_build_core/settings/skbuild_overrides.py
- src/scikit_build_core/settings/skbuild_read_settings.py
Adding a little bit of info from overrides. Later it might be nice to print out the whole set of overridable info, but this will at least help for investigating platforms like iOS.
> chore: show platform info

- docs/about/changelog.md
> docs: update for 0.11.4

- docs/configuration/overrides.md
Fix a typo in a column-name of the `platform-machine` table
> Fix a typo in a column-name of the `platform-machine` table

- docs/conf.py
CI failing due to rate limiting.
> docs: don't link-check GitHub (rate limited)

- docs/about/changelog.md
Quick release so we can start merging stuff for the next major release.
> docs: prepare for 0.11.6
