src/scikit_build_core/cmake.py, src/scikit_build_core/errors.py, src/scikit_build_core/get_requires.py, tests/test_get_requires.py
Adding the core function needed to implement get_requires for various backends.
=> feat: get_requires

.github/codecov.yml, .github/workflows/ci.yml, README.md, noxfile.py
=> ci: add codecov

README.md, src/scikit_build_core/__init__.py, src/scikit_build_core/file_api/__init__.py, src/scikit_build_core/file_api/model/__init__.py, src/scikit_build_core/file_api/model/cache.py, src/scikit_build_core/file_api/model/cmakefiles.py, src/scikit_build_core/file_api/model/codemodel.py, src/scikit_build_core/file_api/model/common.py, src/scikit_build_core/file_api/model/directory.py, src/scikit_build_core/file_api/model/index.py, src/scikit_build_core/file_api/model/toolchains.py, src/scikit_build_core/file_api/query.py, src/scikit_build_core/file_api/reply.py, src/scikit_build_core/get_requires.py, src/scikit_build_core/settings/__init__.py, src/scikit_build_core/settings/cmake_model.py, src/scikit_build_core/settings/cmake_settings.py, src/scikit_build_core/settings/model.py, src/scikit_build_core/settings/sources.py, tests/test_cmake_settings.py, tests/test_get_requires.py, tests/test_module_dir.py
Improves coverage, and ensures the interface is controlled.
=> chore: adding all and better names

.github/workflows/ci.yml, README.md, pyproject.toml, src/scikit_build_core/cmake.py, src/scikit_build_core/get_requires.py, tests/test_cmake_config.py, tests/test_fileapi.py, tests/test_simple_pure.py
Nicer dataclasses.
Also includes the basic layout for including module search paths.
Also including a "pass" CI job when all jobs pass.
=> chore: refactor CMake -> CMake.default_search

.github/workflows/ci.yml, pyproject.toml, src/scikit_build_core/file_api/query.py, tests/test_fileapi.py, tests/test_name_main.py
=> tests: more coverage

src/scikit_build_core/settings/sources.py, tests/test_settings.py
=> fix: better typing for conversions

src/scikit_build_core/_shutil.py, src/scikit_build_core/cmake.py
- refactor: remove keyword args from Run
- fix: implement cwd & env for Run
- feat: add environment support to CMakeConfig
=> refactor: env & remove keyword args for Run

.pre-commit-config.yaml, README.md, pyproject.toml, src/scikit_build_core/cmake.py, src/scikit_build_core/errors.py, src/scikit_build_core/get_requires.py, src/scikit_build_core/program_search.py, src/scikit_build_core/settings/cmake_model.py, tests/test_cmake_config.py, tests/test_fileapi.py, tests/test_get_requires.py, tests/test_program_search.py, tests/test_simple_pure.py, tests/test_skbuild_settings.py
Add ninja and generalize the search for cmake. Also check `cmake3`.
=> refactor: pull out search and improve

src/scikit_build_core/builder/sysconfig.py, tests/test_builder.py
=> feat: add sysconfig helpers

src/scikit_build_core/_compat/__init__.py, src/scikit_build_core/_compat/builtins.py, src/scikit_build_core/_compat/tomllib.py, src/scikit_build_core/_compat/typing.py, src/scikit_build_core/file_api/reply.py, src/scikit_build_core/settings/skbuild_settings.py, src/scikit_build_core/settings/sources.py
=> chore: make compat module

.github/codecov.yml, pyproject.toml, src/scikit_build_core/cmake.py, src/scikit_build_core/pyproject/wheel.py, src/scikit_build_core/setuptools/build_meta.py, tests/simple_pyproject_ext/CMakeLists.txt, tests/simple_setuptools_ext/setup.py, tests/test_pyproject_pep517.py, tests/test_setuptools_pep517.py
=> fix: correct module issue and add tests

src/scikit_build_core/build.py, src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/get_requires.py, src/scikit_build_core/setuptools/build_meta.py, tests/test_get_requires.py
Make a little more sense in here. Not top level.
=> refactor: move get_requires into builder

src/scikit_build_core/build.py, src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/get_requires.py, src/scikit_build_core/setuptools/build_meta.py, tests/test_get_requires.py
- refactor: rename get_requires helper
- chore: slightly better formatting for a file
- feat: include scikit-build-core version
=> refactor: minor naming update

.github/codecov.yml, src/scikit_build_core/builder/get_wheel_tag.py, src/scikit_build_core/cmake.py, src/scikit_build_core/pyproject/sdist.py, src/scikit_build_core/pyproject/wheel.py
=> chore: some cleanup, WheelTag

pyproject.toml, src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/get_wheel_tag.py, src/scikit_build_core/builder/macos.py, src/scikit_build_core/pyproject/wheel.py, tests/test_builder.py
- feat: support cross compiling on macOS
- fix: order version numbers correctly
=> feat: macOS basic cross compiling support

src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/wheel_tag.py, src/scikit_build_core/pyproject/wheel.py, tests/test_builder.py
- refactor: use better wheel_tag name
- fix: support 32-bit Windows native compile
=> fix: windows 32-bit support

src/scikit_build_core/pyproject/wheel.py, tests/simple_pyproject_ext/pyproject.toml, tests/test_pyproject_pep517.py
=> feat: support entrypoints

.github/workflows/cd.yml, .github/workflows/ci.yml, docs/changelog.md, pyproject.toml
Preparing for first PyPI alpha.
- chore: add a changelog, prepare for first test snapshot
- ci: redo distribution setup
=> chore: first alpha

src/scikit_build_core/pyproject/wheel.py
Fix issue with wheel not overwriting old one.
=> fix: avoid copy, avoid failure if pre-existing

.github/CONTRIBUTING.md, pyproject.toml, src/scikit_build_core/_compat/typing.py, src/scikit_build_core/setuptools/extension.py, tests/packages/simple_setuptools_ext/setup.py
Redesigning the setuptools integration, with lots of inspiration from setuptools-rust. This could even be a path forward for scikit-build-classic.
=> feat: use setup keyword support

src/scikit_build_core/builder/macos.py
Should help debug https://github.com/scikit-build/cmake-python-distributions/pull/312.
=> chore: better logging on macOS for deployment target

src/scikit_build_core/builder/builder.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/setuptools/extension.py, tests/test_builder.py, tests/test_skbuild_settings.py
Add way to expand universal tags.
=> feat: extra_tags

src/scikit_build_core/builder/builder.py, src/scikit_build_core/pyproject/wheel.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/setuptools/extension.py, tests/packages/abi3_pyproject_ext/pyproject.toml, tests/test_builder.py, tests/test_skbuild_settings.py
=> refactor(pyproject): tags configuraiton group

src/scikit_build_core/build.py, src/scikit_build_core/pyproject/file_processor.py, src/scikit_build_core/pyproject/sdist.py, src/scikit_build_core/pyproject/wheel.py, tests/packages/simplest_c/CMakeLists.txt, tests/packages/simplest_c/pyproject.toml, tests/test_simplest_c.py
Config will take a bit more thought. Working on #51.
=> feat(pyproject): autocopy packages if names match

.pre-commit-config.yaml, tests/packages/abi3_pyproject_ext/CMakeLists.txt, tests/packages/abi3_setuptools_ext/CMakeLists.txt, tests/packages/simple_pure/CMakeLists.txt, tests/packages/simple_pyproject_ext/CMakeLists.txt, tests/packages/simple_setuptools_ext/CMakeLists.txt, tests/packages/simplest_c/CMakeLists.txt
- chore: drop double COMPONENTS
- chore: add cmake format
- style: run pre-commit on cmake
=> chore: format cmake files

src/scikit_build_core/settings/sources.py, tests/test_settings.py
Lists aren't properly supported, neither are bools. Fixing that.
=> fix: lists and bool settings

src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/get_requires.py, src/scikit_build_core/cmake.py, src/scikit_build_core/program_search.py, src/scikit_build_core/settings/skbuild_model.py, tests/test_builder.py, tests/test_cmake_config.py, tests/test_get_requires.py, tests/test_skbuild_settings.py
Allow make to be used if ninja is not available.
=> fix: fallback to make if available (setting)

README.md, src/scikit_build_core/pyproject/wheel.py, src/scikit_build_core/settings/skbuild_model.py, tests/test_skbuild_settings.py
Packages are automatic unless specified.
=> feat(pyproject): allow python packages to be specified

src/scikit_build_core/pyproject/file_processor.py, src/scikit_build_core/pyproject/sdist.py, src/scikit_build_core/pyproject/wheel.py, src/scikit_build_core/settings/skbuild_model.py, tests/packages/simplest_c/.gitignore, tests/packages/simplest_c/CMakeLists.txt, tests/test_simplest_c.py, tests/test_skbuild_settings.py
Adds the ability to include/exclude files.
=> feat(pyproject): include/exclude

README.md, docs/changelog.md
=> docs: changelog update

src/scikit_build_core/pyproject/wheel.py
This function was getting too big.
=> chore(pyproject): refactor wheel code a bit to read better

.github/CONTRIBUTING.md, src/scikit_build_core/builder/get_requires.py, src/scikit_build_core/pyproject/sdist.py, src/scikit_build_core/pyproject/wheel.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/settings/sources.py, src/scikit_build_core/setuptools/extension.py, tests/test_settings.py, tests/test_skbuild_settings.py
=> feat: strict configuration checking

src/scikit_build_core/settings/skbuild_read_settings.py, tests/test_get_requires.py, tests/test_pyproject_pep517.py, tests/test_simplest_c.py, tests/test_skbuild_settings.py
=> refactor: drop config prefix

src/scikit_build_core/settings/sources.py, tests/test_settings.py
Preparing for #71.
Envvars on windows seem to be case insensitive, so using a singe var approach.
Currently combining vars.
=> feat: dict options

README.md, src/scikit_build_core/builder/builder.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/settings/sources.py, tests/packages/filepath_pure/CMakeLists.txt, tests/packages/filepath_pure/pyproject.toml, tests/test_pyproject_extra_dirs.py, tests/test_skbuild_settings.py
=> feat: support for args/define

README.md, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/settings/skbuild_read_settings.py, tests/test_pyproject_extra_dirs.py, tests/test_skbuild_settings.py
=> feat: min version setting

src/scikit_build_core/_logging.py, src/scikit_build_core/build.py, src/scikit_build_core/pyproject/init.py
Better logging, fixes some issues, and nicer, more succinct printout if CMake fails.
=> fix: better logging

src/scikit_build_core/builder/builder.py, src/scikit_build_core/cmake.py, src/scikit_build_core/settings/skbuild_model.py, tests/test_skbuild_settings.py
=> feat: add verbose setting

.github/CONTRIBUTING.md, src/scikit_build_core/cmake.py, src/scikit_build_core/pyproject/wheel.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/setuptools/extension.py, tests/test_cmake_config.py, tests/test_fileapi.py, tests/test_simple_pure.py, tests/test_skbuild_settings.py
Allow setting a different default or passing it in via `-C`.
=> feat: support specifing a build type

.github/CONTRIBUTING.md, src/scikit_build_core/builder/builder.py, src/scikit_build_core/cmake.py, src/scikit_build_core/pyproject/wheel.py, src/scikit_build_core/setuptools/extension.py, tests/test_cmake_config.py, tests/test_fileapi.py, tests/test_simple_pure.py
Feeling a bit of nostalgia for Scikit-build classic? This is just the ticket. :)
(I was originally trying to use a different name, but this is a better name)
=> refactor: CMakeConfig -> CMaker

tests/test_cmake_config.py
These tests can be run even if cmake is not installed.
=> tests: run more tests without the cmake module

pyproject.toml, tests/packages/simple_pyproject_ext/pyproject.toml, tests/test_pyproject_pep517.py, tests/test_pyproject_pep518.py
This is more about getting rich tracebacks; normal rich-less runs may be also in color soon.
=> refactor: rename extra color -> rich

src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/wheel_tag.py, tests/test_builder.py
=> fix: universal2 tags computation was incorrect again

src/scikit_build_core/cmake.py
MinGW Makefiles, and probably others.
=> fix: guess single config for more generators

tests/test_builder.py
=> tests: xfail a non-important test

src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/get_requires.py
=> fix: support pre-set generators

.github/workflows/ci.yml
Testing this out. Have no idea what I'm doing here.
=> ci: add msys2

tests/conftest.py, tests/test_pyproject_pep518.py, tests/test_setuptools_pep518.py
=> tests: cleanup a bit

.pre-commit-config.yaml, README.md, docs/changelog.md, src/scikit_build_core/build/__init__.py, src/scikit_build_core/builder/builder.py, src/scikit_build_core/file_api/reply.py, src/scikit_build_core/setuptools/extension.py
- chore: minor cleanup from refurb and shed
- docs: prepare for 0.1.0
- chore: update pre-commit for better commit messages
=> chore: prepare for 0.1.0

src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/generator.py, tests/test_generator_default.py
Uses the CMake help text (not ideal, but only fast way to get this info that I know of using the full CMake generator search logic on Windows).
=> fix: compute the correct default generator for CMake

tests/test_fileapi.py, tests/test_simple_pure.py
Support missing make when running tests.
=> tests: support make missing

src/scikit_build_core/builder/generator.py
=> fix: win32 issue

src/scikit_build_core/build/wheel.py
The final value was being added. This was/is protected under an experimental flag, but it wasn't supposed to be broken. :)
=> fix: issue with expiremental extra directory targeting

.github/workflows/ci.yml
Fixes the "pass on fail" feature of the previous implementation. Thanks to @webknjaz in https://github.com/pypa/build/pull/543 and https://github.com/mesonbuild/meson-python/pull/221#discussion_r1038060140.
=> ci: fix pass job

.gitignore, tests/conftest.py, tests/test_simple_pure.py
=> fix: working on Windows ARM

src/scikit_build_core/_shutil.py, src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/generator.py
Fixes #165
Also adding more debugging info.
=> fix: ninja path not being set correctly

src/scikit_build_core/builder/generator.py
=> fix: minor touchup to ninja / make

.flake8, .pre-commit-config.yaml, pyproject.toml, src/scikit_build_core/build/__init__.py, src/scikit_build_core/build/_file_processor.py, src/scikit_build_core/build/sdist.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/builder.py, src/scikit_build_core/builder/generator.py, src/scikit_build_core/builder/get_requires.py, src/scikit_build_core/builder/sysconfig.py, src/scikit_build_core/file_api/reply.py, src/scikit_build_core/settings/sources.py, src/scikit_build_core/setuptools/build_meta.py, src/scikit_build_core/setuptools/extension.py, tests/conftest.py, tests/test_builder.py, tests/test_cmake_config.py, tests/test_fileapi.py, tests/test_program_search.py, tests/test_pyproject_abi3.py, tests/test_pyproject_extra_dirs.py, tests/test_pyproject_pep517.py, tests/test_pyproject_pep518.py, tests/test_settings.py, tests/test_setuptools_abi3.py, tests/test_setuptools_pep517.py, tests/test_setuptools_pep518.py, tests/test_simple_pure.py, tests/test_simplest_c.py
Trying this out. Very impressed so far. Some minor issues, but very complete, fast, and simple. No more `.flake8` file!
=> chore: use ruff

pyproject.toml, src/scikit_build_core/builder/wheel_tag.py, src/scikit_build_core/cmake.py, src/scikit_build_core/file_api/_cattrs_converter.py, src/scikit_build_core/file_api/reply.py, src/scikit_build_core/settings/sources.py
- chore: add Ruff EM check
- chore: add pathlib check
=> chore: Ruff related additions

pyproject.toml, tests/test_cmake_config.py, tests/test_get_requires.py, tests/test_program_search.py
First step: use Path directly in register
Second step: use Program
=> tests: simpler subprocess

.pre-commit-config.yaml, src/scikit_build_core/_shutil.py, src/scikit_build_core/builder/get_requires.py, tests/test_cmake_config.py, tests/test_fileapi.py, tests/test_pyproject_pep517.py, tests/test_settings.py
=> chore: move to black 23

pyproject.toml, src/scikit_build_core/build/__init__.py, src/scikit_build_core/build/_wheelfile.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/wheel_tag.py, tests/conftest.py, tests/constraints.txt, tests/test_module_dir.py, tests/test_wheelfile_utils.py
Should enable further work on prepare metadata and editable installs, and drops a dependency (distlib).
=> refactor: native wheel writer implementation

.pre-commit-config.yaml, src/scikit_build_core/build/__init__.py, src/scikit_build_core/build/_wheelfile.py, src/scikit_build_core/build/sdist.py, src/scikit_build_core/build/wheel.py, tests/test_pyproject_pep517.py, tests/test_pyproject_pep518.py
This is a simple implementation of `prepare_metadata_for_build_wheel`.
=> feat: prepare_metadata_for_build_wheel

src/scikit_build_core/build/__init__.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/__init__.py
- docs: adding a note about build vs builder
- chore: return structured data from wheel impl
=> chore: minor adustments to wheel returns

src/scikit_build_core/build/_wheelfile.py, src/scikit_build_core/build/wheel.py, tests/conftest.py
=> test: nicer exit, minor refactors

noxfile.py, src/scikit_build_core/_shutil.py, src/scikit_build_core/build/_pathutil.py, src/scikit_build_core/build/wheel.py
=> refactor: minor changes from editable work

src/scikit_build_core/builder/wheel_tag.py
=> fix: Windows ARM tag

src/scikit_build_core/builder/wheel_tag.py
See https://github.com/scikit-build/scikit-build-core/pull/197/files/effad2106dad834e21ee72b8c42351c35ab0e21c..024f69b78bc490d83f4b9d64bd4de012617394da#r1132655974.
=> chore: fix a mypy complaint on Windows

tests/conftest.py
Little cleanup, and report self version.
=> tests: report self version too

.pre-commit-config.yaml, pyproject.toml, tests/test_fileapi.py, tests/test_skbuild_settings.py
Just a bit of cleanup. See https://github.com/charliermarsh/ruff/issues/3503.
=> chore: improve empty string Ruff supression

docs/api/scikit_build_core.metadata.rst, docs/api/scikit_build_core.rst, docs/api/scikit_build_core.settings.rst, docs/conf.py, docs/configuration.md, docs/getting_started.md, docs/index.md, noxfile.py, pyproject.toml
- docs: tabbed example page
- docs: add config page
=> docs: tabbed quickstart, added config page

.pre-commit-config.yaml, src/scikit_build_core/setuptools/extension.py
Quick update for recent added typing.
=> chore: fix more setuptools types

.github/workflows/ci.yml, README.md, docs/cmakelists.md, docs/configuration.md, docs/examples/getting_started/abi3/CMakeLists.txt, docs/examples/getting_started/abi3/example.c, docs/examples/getting_started/abi3/pyproject.toml, docs/examples/getting_started/c/CMakeLists.txt, docs/examples/getting_started/c/example.c, docs/examples/getting_started/c/pyproject.toml, docs/examples/getting_started/pybind11/CMakeLists.txt, docs/examples/getting_started/pybind11/example.cpp, docs/examples/getting_started/pybind11/pyproject.toml, docs/examples/getting_started/test.py, docs/getting_started.md, docs/index.md, noxfile.py
- docs: more tabbed selections
- docs: CMakeLists.txt info
- docs: include metadata in readme
- docs: include ABI3 in examples
- docs: seperate example files
- ci: check docs
=> docs: examples testing & cmake help

pyproject.toml, tests/packages/fortran_example/CMakeLists.txt, tests/packages/fortran_example/fib1.f, tests/packages/fortran_example/pyproject.toml, tests/test_fortran.py
=> tests: add fortran test

docs/examples/getting_started/fortran/CMakeLists.txt, docs/examples/getting_started/fortran/example.f, docs/examples/getting_started/fortran/pyproject.toml, docs/getting_started.md, noxfile.py
=> docs: add Fortran example

src/scikit_build_core/builder/get_requires.py, tests/test_get_requires.py
Refactoring in preparation for #236.
=> fix: restructure get_requires & fix some ninja paths

.gitignore, .pre-commit-config.yaml, pyproject.toml
Adds a few missing bits to the .gitignore
=> chore: add sdist check & fix

docs/configuration.md, src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/get_requires.py, src/scikit_build_core/metadata/fancy_pypi_readme.py, src/scikit_build_core/settings/_load_provider.py, src/scikit_build_core/settings/metadata.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/settings/sources.py, tests/packages/dynamic_metadata/dual_project.toml, tests/packages/dynamic_metadata/faulty_dual_project.toml, tests/packages/dynamic_metadata/faulty_project.toml, tests/packages/dynamic_metadata/local_pyproject.toml, tests/packages/dynamic_metadata/plugin_project.toml, tests/packages/dynamic_metadata/plugins/local/version/nested/__init__.py, tests/packages/dynamic_metadata/pyproject.toml, tests/test_dynamic_metadata.py, tests/test_settings.py, tests/test_skbuild_settings.py
Closer to current proposal, closes #236.
New features:
* Uses `provider =`
* New `provider-path =` for local plugins
* Custom or local plugins require `tool.scikit-build.experimental=true` to use, since API is not stable yet.
* `Dict[str, Any]` support for TOML reader.
=> feat: rework plugins

src/scikit_build_core/build/_scripts.py, src/scikit_build_core/build/wheel.py, tests/test_process_scripts.py
Closes #130. Properly processes and rewrites script's shebang lines.
=> fix: support script rewriting

tests/conftest.py, tests/test_dynamic_metadata.py, tests/test_pyproject_extra_dirs.py, tests/test_pyproject_pep517.py, tests/test_pyproject_pep518.py, tests/test_setuptools_pep517.py, tests/test_setuptools_pep518.py
=> tests: use fixtures for packages

docs/examples/getting_started/abi3/example.c, docs/examples/getting_started/c/example.c, tests/packages/abi3_pyproject_ext/abi3_example.c, tests/packages/abi3_setuptools_ext/abi3_example.c, tests/packages/dynamic_metadata/src/module.c, tests/packages/simplest_c/src/module.c
- tests: fix simplest_c name
- docs: fix example module names
=> docs: fix internal module names

.pre-commit-config.yaml, pyproject.toml, src/scikit_build_core/build/wheel.py, tests/test_dynamic_metadata.py
Sadly `Path` takes `**kwargs` and ignores them.
=> fix: wheel_tag was not working

src/scikit_build_core/builder/builder.py
Similar to https://github.com/scikit-build/scikit-build/pull/913.
=> fix: add python library artifact

.github/codecov.yml, .github/workflows/ci.yml, docs/changelog.md
Preparing changelog. Might do a little more before release, but we are probably pretty close, especially in terms of features.
=> docs: update changelog for 0.3.0

src/scikit_build_core/_logging.py, tests/test_logging.py
=> fix: support colors without Rich present

.github/workflows/ci.yml, noxfile.py, pyproject.toml
=> tests: adjust coverage, use --cov in nox

.github/CONTRIBUTING.md, .pre-commit-config.yaml, docs/configuration.md
=> docs: fix incorrect tool name

docs/configuration.md
=> docs: fix wheel.packages

docs/configuration.md
=> docs: add a bit to plugin instructions

src/scikit_build_core/build/_scripts.py
=> fix: suppress Unicode errors and move on

pyproject.toml, src/scikit_build_core/builder/builder.py, src/scikit_build_core/file_api/_cattrs_converter.py, src/scikit_build_core/file_api/reply.py
Adding some enforcement for `_compat` code.
=> chore: add some Ruff enforcements for _compat

.github/workflows/cd.yml
=> ci: use trusted publisher deployment

docs/examples/getting_started/fortran/CMakeLists.txt, docs/examples/getting_started/fortran/pyproject.toml, noxfile.py, pyproject.toml, src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/generator.py, tests/packages/fortran_example/CMakeLists.txt, tests/test_fortran.py
Also adds a way to test downstream packages manually.
=> fix: ninja wasn't being used if present

.github/workflows/ci.yml, docs/api/scikit_build_core.setuptools.rst, src/scikit_build_core/setuptools/wrapper.py
Also small fix for coverage (I hope).
=> feat(setuptools): adding wrapper for skbuild compat

README.md, docs/configuration.md, src/scikit_build_core/build/wheel.py, src/scikit_build_core/settings/skbuild_model.py, tests/conftest.py, tests/packages/simple_pyproject_ext/LICENSE, tests/packages/simple_setuptools_ext/LICENSE, tests/packages/simple_setuptools_ext/setup.py, tests/test_pyproject_pep517.py, tests/test_pyproject_pep518.py, tests/test_setuptools_pep517.py, tests/test_skbuild_settings.py
Makes sure LICENSE files are included, and adds a setting to find them.
=> fix: add LICENSE file

src/scikit_build_core/build/wheel.py, src/scikit_build_core/settings/skbuild_model.py, tests/conftest.py, tests/packages/simple_pyproject_source_dir/LICENSE, tests/packages/simple_pyproject_source_dir/pyproject.toml, tests/packages/simple_pyproject_source_dir/src/CMakeLists.txt, tests/packages/simple_pyproject_source_dir/src/main.cpp, tests/test_pyproject_pep517.py, tests/test_skbuild_settings.py
=> feat: source-dir for pyproject.toml

docs/changelog.md, src/scikit_build_core/build/wheel.py, tests/test_pyproject_pep517.py, tests/test_pyproject_pep518.py
Yanked 0.4.0. Will release 0.4.1 once this goes in.
=> fix: LICENSE files were placed in the wrong place

.github/workflows/cd.yml, docs/changelog.md, pyproject.toml
- chore: add better links to metadata
- docs: clean up changelog extra headers
=> chore: docs & links

README.md, docs/cmakelists.md
Some updates, includes a mention of #333.
=> docs: some updates

src/scikit_build_core/settings/sources.py
Working on refactoring settings. Cleanup to prepare for overrides.
- fix: raise `TypeError` if item not convertible
- refactor: `SourceChain` no longer a `Source`
=> refactor: settings

src/scikit_build_core/builder/builder.py
Easier to use in a CMakeLists.
=> refactor: better name and value for SABI

src/scikit_build_core/build/wheel.py, src/scikit_build_core/resources/_editable_redirect.py
=> fix: editable installs with multiconfig generators

src/scikit_build_core/build/_file_processor.py, tests/test_file_processor.py
=> fix: follow symlinks when making SDists

tests/packages/custom_cmake/CMakeLists.txt, tests/packages/custom_cmake/scripts/script1, tests/test_custom_modules.py
=> tests: add testing for scripts processing

src/scikit_build_core/_logging.py, src/scikit_build_core/_shutil.py, src/scikit_build_core/build/wheel.py
- fix: smarter printout of changes
- fix: flush printer
- fix: more details from color printout
=> fix: proper printout ordering and more details

.github/workflows/ci.yml, .pre-commit-config.yaml, README.md, docs/conf.py, noxfile.py, src/scikit_build_core/settings/skbuild_model.py
Fixing #369 (hopefully, at least most of it).
=> docs: fix or hide nitpicks

.github/workflows/ci.yml, docs/conf.py, docs/index.md, docs/man.md, pyproject.toml
Just puts the README in as the man page.
=> fix: support man pages

docs/examples/getting_started/nanobind/CMakeLists.txt, docs/examples/getting_started/nanobind/example.cpp, docs/examples/getting_started/nanobind/pyproject.toml, docs/getting_started.md, noxfile.py
=> docs: add nanobind example

docs/examples/getting_started/swig/CMakeLists.txt
=> docs: use UseSWIG for swig

.distro/python-scikit-build-core.spec
=> ci: use not network for spec

src/scikit_build_core/build/wheel.py
See https://github.com/scikit-build/scikit-build-core/issues/392#issuecomment-1601125373.
=> fix: provide access to scikit-build state

.github/workflows/ci.yml, noxfile.py, pyproject.toml
Fixing #382 again. IIRC underscores are the preferred symbol in extras? Edit: no, it normalizes to dashes.
=> fix: second try at reworking extras

tests/conftest.py
=> tests: get packages of interest from pyproject.toml

tests/test_logging.py
=> fix: support running tests with NO_COLOR

.pre-commit-config.yaml, noxfile.py, pyproject.toml
Adding mypy checking found three (edit: technically two, the Path/str one is a bug in nox's types, I think) bugs in the noxfile. One of them closes #404.
=> fix: noxfile added to mypy, three fixes

src/scikit_build_core/_shutil.py
=> fix: logging environment should use reprs

.pre-commit-config.yaml, docs/changelog.md, pyproject.toml, src/scikit_build_core/builder/builder.py, src/scikit_build_core/settings/sources.py, src/scikit_build_core/setuptools/build_cmake.py, tests/test_fileapi.py
A few things getting ready for a patch release.
- chore: pyproject.toml cleanup and bump pre-commit
- docs: add changelog
=> chore: bumps & changelog

docs/examples/test.sh
Probably a design flaw upstream, but this should be a quick fix in the meantime
https://github.com/teemtee/tmt/issues/2184
=> packaging: Fix fedora downstream tests

docs/getting_started.md
The Getting Started docs worked great for me when I followed the instructions for `C`. Here are a few small suggestions.
=> Small suggestions for docs

.github/CONTRIBUTING.md, docs/getting_started.md
=> docs: fix nanobind/pybind11 src & sp-dev

docs/conf.py
=> docs: link to source

README.md, docs/configuration.md, src/scikit_build_core/builder/builder.py, src/scikit_build_core/cmake.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/settings/skbuild_read_settings.py, tests/packages/simplest_c/CMakeLists.txt, tests/test_simplest_c.py, tests/test_skbuild_settings.py
This adds support for components & stripping. Stripping only applied by default if scikit-build-core version > 0.5.
=> feat: add component support

README.md, docs/configuration.md, src/scikit_build_core/builder/builder.py, src/scikit_build_core/cmake.py, src/scikit_build_core/settings/skbuild_model.py, tests/test_pyproject_pep517.py, tests/test_skbuild_settings.py
=> feat: add build target support

docs/conf.py, docs/configuration.md, docs/ext/conftabs.py
- docs: refactor tabs to plugin
=> docs: conf tabs as extension

src/scikit_build_core/setuptools/build_cmake.py
=> fix(setuptools): avoid instantiating build too soon

src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/json_schema.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/settings/sources.py, tests/test_schema.py, tests/test_settings.py
Better schema validation, more immediate feedback for invalid literals, better typing.
Will help with #459.
=> fix: support Literals in settings

pyproject.toml, src/scikit_build_core/build/_file_processor.py, src/scikit_build_core/build/sdist.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/builder.py, src/scikit_build_core/resources/__init__.py, src/scikit_build_core/setuptools/build_cmake.py
Tiny bit of cleanup.
- chore: clean up some uneeded types
- chore: hide a repo-review FP
=> chore: clean up some extraneous types

.github/workflows/ci.yml
PyPy is starting to timeout. Increase timeouts a bit.
=> ci: increase timeout (PyPy slow)

.pre-commit-config.yaml, README.md, docs/api/scikit_build_core.build.rst, docs/configuration.md, src/scikit_build_core/_compat/typing.py, src/scikit_build_core/build/generate.py, src/scikit_build_core/build/sdist.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/documentation.py, src/scikit_build_core/settings/json_schema.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/settings/skbuild_schema.py, src/scikit_build_core/settings/sources.py, tests/packages/sdist_config/.gitignore, tests/packages/sdist_config/CMakeLists.txt, tests/packages/sdist_config/input.cmake, tests/packages/sdist_config/pyproject.toml, tests/test_json_schema.py, tests/test_pyproject_pep518.py, tests/test_schema.py, tests/test_settings.py, tests/test_skbuild_settings.py
=> feat: write metadata to file

pyproject.toml
Temporary fix while waiting for https://github.com/pypa/setuptools/pull/4023.
=> docs: patch for circular import issue with setuptools

README.md
After releasing `nox -s readme` has to be rerun. Also updating readme and adding discord badge.
=> docs: update and add discord link

noxfile.py
Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>
=> chore: nicer nox for docs

docs/configuration.md
See https://github.com/scikit-build/scikit-build-core/blob/f5bad6241069bd09b59e64befb93e78a0d0c907d/src/scikit_build_core/settings/skbuild_read_settings.py#L123
=> fix: fix template-file with template-path

docs/configuration.md
change p to P in (?P<name>...)
I'm just testing the regex feature.
=> A single-letter change in configuration.md

docs/configuration.md, docs/ext/conftabs.py, src/scikit_build_core/setuptools/build_cmake.py
=> fix(setuptools): support build type set in toml

docs/changelog.md, docs/cmakelists.md, docs/crosscompile.md, docs/index.md
Some docs additions. Works toward addressing https://github.com/scikit-build/scikit-build/issues/1013.
=> docs: cross compile additions & authoring additions

.pre-commit-config.yaml, README.md, docs/configuration.md, src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/settings/skbuild_schema.py, tests/test_schema.py, tests/test_settings_overrides.py
Closes #332. Needs docs and a few more tests (like regex test, unrecognized key).
=> feat: adding overrides

.pre-commit-config.yaml, docs/getting_started.md, src/scikit_build_core/build/sdist.py
Small fixes for pylint & pre-commit updates.
=> chore: pre-commit update & a couple of touchups

src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/skbuild_schema.py, tests/test_schema.py
Noticed when working on submitting to SchemaStore.
=> fix(schema): a typo and better metadata support

docs/build.md, docs/examples/getting_started/ctypes/CMakeLists.txt, docs/examples/getting_started/ctypes/example.c, docs/examples/getting_started/ctypes/pyproject.toml, docs/examples/getting_started/ctypes/src/example/__init__.py, docs/faqs.md, docs/index.md
=> docs: build process and faq

.pre-commit-config.yaml, pyproject.toml
Some small things noticed while working on sp-repo-review. https://github.com/scientific-python/cookie/pull/299 and https://github.com/scientific-python/cookie/pull/300 and https://github.com/scientific-python/repo-review/pull/152.
=> fix: small updates from repo-review

src/scikit_build_core/build/_editable.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/resources/_editable_redirect.py, tests/conftest.py, tests/test_editable_unit.py
Adding a unit test for editable installs, break out some handling.
=> tests: refactor and unit test editable install

src/scikit_build_core/builder/builder.py
I think this would help with https://github.com/scikit-build/scikit-build-core/issues/542.
=> fix: filter CMAKE_ARGS and debug printout

docs/configuration.md, src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/settings/skbuild_schema.py, tests/test_settings_overrides.py
Adds support for using `if.any` in overrides.
=> feat: support if.any

docs/configuration.md, pyproject.toml, src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/settings/skbuild_schema.py, tests/test_settings_overrides.py
Adding support for if.env, for custom environment variables.
=> feat: support if.env

README.md
Add link & update intro text to be a bit more general.
=> docs: update intro and mention cmeel

README.md, docs/index.md
=> docs: add meeting information

docs/changelog.md
=> chore: preapre for 0.7.0

docs/changelog.md, docs/getting_started.md, docs/migration_guide.md
=> docs: fix a link

pyproject.toml
=> chore: remove deprecated mypy setting (now defaults on)

.pre-commit-config.yaml, src/scikit_build_core/metadata/fancy_pypi_readme.py
Quick fix for the change introduced in https://github.com/hynek/hatch-fancy-pypi-readme/pull/39 and noticed in https://github.com/scikit-build/scikit-build-core/issues/592.
=> fix: patch for change in dynamic-metadata

docs/changelog.md
=> docs: prepare for 0.7.1

.pre-commit-config.yaml, pyproject.toml, src/scikit_build_core/metadata/fancy_pypi_readme.py
Fix a minor typing change in hatch-fancy-pypi-readme 24.1, and try to ensure pytest isn't too greedy (might help with #598).
=> chore: a couple of minor cleanups

docs/configuration.md, src/scikit_build_core/build/sdist.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/settings/skbuild_schema.py, tests/test_dynamic_metadata.py, tests/test_settings_overrides.py
This is the easier of the two suggestions in #591.
=> feat: add if.state to overrides

docs/cmakelists.md, src/scikit_build_core/builder/builder.py
=> fix: project version should be CMake parsable

README.md, src/scikit_build_core/build/_wheelfile.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/wheel_tag.py, src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/skbuild_model.py, tests/test_builder.py, tests/test_pyproject_pep517.py, tests/test_skbuild_settings.py
=> feat: add build-tag

src/scikit_build_core/build/_wheelfile.py, src/scikit_build_core/build/wheel.py, tests/test_wheelfile_utils.py
Was cleaning up, and noticed a small bug in the WHEEL metadata if setting purelib.
=> fix: make sure purelib is indicated

README.md, docs/changelog.md
=> docs: prepare for 0.8.0

.github/CONTRIBUTING.md
=> docs: correct API usage example

src/scikit_build_core/cmake.py, tests/test_cmake_config.py
=> fix: include CMAKE_BUILD_TYPE on Windows Ninja

src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/wheel_tag.py, tests/test_pyproject_purelib.py
=> fix: Ensure wheel.platlib being false sets <abi>-<platform> as "none-any"

src/scikit_build_core/_logging.py, src/scikit_build_core/builder/__main__.py, src/scikit_build_core/builder/sysconfig.py, src/scikit_build_core/program_search.py, tests/test_printouts.py
Add info print functionality to a few more modules
=> fix: expand info printing

docs/changelog.md
=> chore: prepare for 0.8.2

docs/cmakelists.md, docs/configuration.md, docs/faqs.md, src/scikit_build_core/builder/__main__.py
=> docs: mention printouts

.distro/python-scikit-build-core.spec
https://src.fedoraproject.org/rpms/python-scikit-build-core/pull-request/49
=> fedora: Port downstream PR-49

src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/setuptools/build_cmake.py, tests/test_settings_overrides.py, tests/test_skbuild_settings.py
A little bit of optimization for plugin use, such as #637.
=> refactor: make from_file a little more powerful

docs/cmakelists.md, src/scikit_build_core/_compat/importlib/metadata.py, src/scikit_build_core/build/_wheelfile.py, src/scikit_build_core/build/wheel.py, tests/packages/simplest_c/CMakeLists.txt, tests/test_builder.py, tests/test_pyproject_pep517.py, tests/test_simplest_c.py, tests/test_wheelfile_utils.py
Mentioned in https://github.com/scikit-build/scikit-build-core/issues/666.
=> feat: add metadata dir access

.git_archival.txt
Context: https://github.com/pypa/setuptools_scm/issues/806
Closes #695
=> fix: Make .git_archival.txt reproducible

.pre-commit-config.yaml, docs/conf.py, noxfile.py, pyproject.toml, src/scikit_build_core/_vendor/pyproject_metadata/LICENSE, src/scikit_build_core/_vendor/pyproject_metadata/__init__.py, src/scikit_build_core/build/__init__.py, src/scikit_build_core/build/_wheelfile.py, src/scikit_build_core/build/generate.py, src/scikit_build_core/build/metadata.py, tests/test_dynamic_metadata.py, tests/test_get_requires.py, tests/test_wheelfile_utils.py
This will enable us to use new features immediately.
Close #688.
Need to ignore the vendored file in a few places like coverage.
=> feat: vendor pyproject-metadata

.github/CONTRIBUTING.md, docs/changelog.md
=> chore: prepare for 0.9.0

src/scikit_build_core/hatch/plugin.py
https://hatch.pypa.io/latest/plugins/builder/wheel/#versions
=> Properly indicate lack of editable support in Hatch plugin

docs/cmakelists.md
From helping with https://github.com/dcwatson/deflate.
=> docs: update stable ABI instructions

.github/workflows/ci.yml
=> ci: retry pypy if fails

.github/workflows/ci.yml, .pre-commit-config.yaml, docs/faqs.md, src/scikit_build_core/_logging.py, tests/test_logging.py
Fixes #763
Only replace the rich tag if the color is defined in `colors()`
=> Only replace rich if the color is defined

docs/cmakelists.md, pyproject.toml
See https://github.com/scikit-build/scikit-build-core/issues/774.
=> docs: fix typo in skbuild soabi docs

src/scikit_build_core/builder/wheel_tag.py
=> fix: musllinux tag incorrect

README.md, docs/getting_started.md, pyproject.toml, tests/packages/cython_pxd_editable/pkg1/CMakeLists.txt, tests/packages/cython_pxd_editable/pkg2/CMakeLists.txt, tests/packages/fortran_example/CMakeLists.txt
Updates based on recent Fortran and Cython work.
=> docs: Fortran and Cython updates

src/scikit_build_core/builder/generator.py
Should help with Fortran compiling.
=> fix: set CC and CXX from sysconfig if not set

.github/workflows/cd.yml, docs/changelog.md, pyproject.toml, tests/conftest.py
=> docs: prepare for 0.9.7

.github/workflows/ci.yml, .pre-commit-config.yaml, docs/getting_started.md, pyproject.toml, tests/test_dynamic_metadata.py, tests/test_fortran.py, tests/test_pyproject_abi3.py, tests/test_pyproject_extra_dirs.py, tests/test_pyproject_pep517.py, tests/test_pyproject_pep518.py, tests/test_pyproject_pep660.py, tests/test_setuptools_abi3.py, tests/test_setuptools_pep517.py, tests/test_setuptools_pep518.py, tests/test_simplest_c.py, tests/utils/pathutils.py
A better fit in general, and doesn't require Python 3.8.
=> tests: use zipfile

src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/builder.py, src/scikit_build_core/cmake.py, src/scikit_build_core/hatch/plugin.py, src/scikit_build_core/setuptools/build_cmake.py
=> fix: support packages that hardcode CMAKE_INSTALL_PREFIX in their install commands

.pre-commit-config.yaml, docs/conf.py, docs/data/projects.toml, docs/index.md, docs/projects.md
Add the long-promised projects list.
=> docs: add projects list

docs/configuration.md, docs/index.md, docs/schema.md
Fix https://github.com/scikit-build/scikit-build-core/issues/794.
=> docs: expand defs and move schema

noxfile.py
=> docs: examples nox job should use local copy of scikit-build-core

docs/configuration.md, docs/index.md, docs/overrides.md, docs/schema.md
This needs to be expanded and made its own page.
=> docs: move overrides to page, expand

docs/projects.md
This is an example of a realistic, more complex scikit-build-core SWIG
project that also sparked the origin of scikit-build.
There are also many additional examples referenced here:
https://github.com/InsightSoftwareConsortium/ITK/issues/4748
=> docs: add pointer to itk

.pre-commit-config.yaml, docs/overrides.md, src/scikit_build_core/resources/known_wheels.toml, src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/skbuild_overrides.py, src/scikit_build_core/settings/skbuild_schema.py, tests/conftest.py, tests/test_get_requires.py, tests/test_settings_overrides.py
=> feat: adding if.system-cmake and if.cmake-wheel

src/scikit_build_core/build/_file_processor.py, tests/test_file_processor.py
Supports nested gitignores and `.git/info/exclude`. Close https://github.com/scikit-build/scikit-build-core/issues/726.
As a followup, we could add a `sdist.ignore-system = ["git", "local"]` or similar, which would allow scikit-build-core to directly use git.
=> fix: support nested and local gitignores

src/scikit_build_core/program_search.py
=> fix: regresssion for '-' in version name

README.md, docs/configuration.md, src/scikit_build_core/build/_pathutil.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/resources/scikit-build.schema.json, src/scikit_build_core/settings/json_schema.py, src/scikit_build_core/settings/skbuild_model.py, src/scikit_build_core/settings/skbuild_read_settings.py, src/scikit_build_core/settings/skbuild_schema.py, src/scikit_build_core/settings/sources.py, tests/test_editable_unit.py, tests/test_settings.py
This is an implementation of #669.
=> feat: package table

docs/configuration.md, pyproject.toml, src/scikit_build_core/_logging.py, src/scikit_build_core/ast/ast.py, src/scikit_build_core/ast/tokenizer.py, src/scikit_build_core/build/__init__.py, src/scikit_build_core/build/sdist.py, src/scikit_build_core/build/wheel.py, src/scikit_build_core/builder/__main__.py, src/scikit_build_core/builder/sysconfig.py, src/scikit_build_core/hatch/plugin.py, src/scikit_build_core/program_search.py, src/scikit_build_core/settings/skbuild_read_settings.py, tests/test_logging.py
=> feat: new color system

src/scikit_build_core/program_search.py, tests/test_cmake_config.py
Trying a potential fix for #843.
=> fix: expand some variables when constructing paths

docs/changelog.md, docs/configuration.md, docs/overrides.md, docs/plugins/hatchling.md, noxfile.py, src/scikit_build_core/build/wheel.py
=> docs: prepare for 0.10.0

docs/changelog.md, src/scikit_build_core/program_search.py, tests/test_cmake_config.py
Reverts scikit-build/scikit-build-core#844
=> Revert "fix: expand some variables when constructing paths"

.github/workflows/ci.yml, pyproject.toml
=> ci: avoid wheel warning with old setuptools

docs/changelog.md, docs/configuration.md
=> docs: fix multipart regex example

.pre-commit-config.yaml, README.md, docs/faqs.md, src/scikit_build_core/setuptools/build_cmake.py
=> docs: add conda help to faqs

.pre-commit-config.yaml, docs/build.md, pyproject.toml, tests/conftest.py, tests/test_broken_fallback.py, tests/test_cmake_config.py, tests/test_dynamic_metadata.py, tests/test_editable.py, tests/test_fileapi.py, tests/test_fortran.py, tests/test_get_requires.py, tests/test_hatchling.py, tests/test_pyproject_abi3.py, tests/test_pyproject_extra_dirs.py, tests/test_pyproject_pep517.py, tests/test_pyproject_pep518.py, tests/test_pyproject_pep660.py, tests/test_pyproject_purelib.py, tests/test_setuptools_abi3.py, tests/test_setuptools_pep517.py, tests/test_setuptools_pep518.py, tests/test_shutil.py, tests/test_simple_pure.py, tests/test_simplest_c.py
Adding a few things, mostly a docs update with more help debugging builds.
=> docs: add build info

src/scikit_build_core/build/metadata.py
Reported in https://github.com/rapidfuzz/RapidFuzz/pull/397.
=> fix: avoid modifing the input dict

.github/workflows/ci.yml
Fixes the warnings about "latest"
=> ci: use astral-sh/setup-uv instead

.github/workflows/ci.yml, .pre-commit-config.yaml, docs/build.md, docs/changelog.md, docs/configuration.md, docs/data/projects.toml, docs/examples/downstream/nanobind_example/README.md, docs/examples/downstream/pybind11_example/README.md, docs/faqs.md, docs/overrides.md, docs/projects.md, pyproject.toml
=> chore: update pre-commit checks

.pre-commit-config.yaml, docs/getting_started.md, pyproject.toml, src/scikit_build_core/file_api/reply.py, src/scikit_build_core/settings/documentation.py, src/scikit_build_core/settings/json_schema.py, src/scikit_build_core/settings/sources.py
Also fixing up some config and updating mypy.
- **docs: quick start in getting started**
- **chore: bump deps**
=> docs: quickstart updates

src/scikit_build_core/setuptools/build_cmake.py, tests/conftest.py, tests/packages/toml_setuptools_ext/CMakeLists.txt, tests/packages/toml_setuptools_ext/LICENSE, tests/packages/toml_setuptools_ext/pyproject.toml, tests/packages/toml_setuptools_ext/src/main.cpp, tests/test_setuptools_pep517.py
Support for setuptools extensions without a setup.py.
=> feat: setuptools pyproject-toml only config support

.github/workflows/cd.yml, .github/workflows/ci.yml
Some suggestions from [Zizmor](https://woodruffw.github.io/zizmor/).
=> ci: tighten up permissions a bit

docs/conf.py, pyproject.toml
Let's make it pretty :slightly_smiling_face:.
There is also [sphinx-hoverxref](https://github.com/readthedocs/sphinx-hoverxref), but I forgot what the issue was with that and markdown support
=> Add sphinx-tippy

.github/workflows/ci.yml, pyproject.toml
The new Windows ARM runner is available.
=> ci: add Windows ARM

noxfile.py, pyproject.toml
Updating the setup for code coverage a bit, largely based on pypa/build's setup.
=> chore: update coverage a bit

.github/workflows/ci.yml, .pre-commit-config.yaml, docs/about/projects.md, docs/data/projects.toml
The cogging of pages was broken when the pages got moved around. Fixed and reran the top X projects scripts.
=> docs: update and fix projects list

docs/about/changelog.md
Ready for a small release from PyCon.
=> docs: prepare for 0.11.3

pyproject.toml
I think this will help in adding this project to mypy-primer.
=> chore: explicit mypy ignores
